### ISSUE TITLE
Moissonnage a minima pour la release

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#105]
Moissonner au minimum les catalogues du périmètre Auvergne-Rhône-Alpes : 
- [x] GeoIDE DDTs
- [x] GeoIDE DGALN ?
- [ ] DatARA

Attention à https://github.com/ecolabdata/ecospheres/issues/55

**Comment by Thesauruv** [comment]
Pour le moissonnage de DatARA, nous pouvons a minima partir sur deux organisations : DREAL ARA, Métropole de Lyon. Les autres sont également intéressantes (Cerema, BRGM, ORE, Sandre, Patrinat, etc.). Concernant les organisations des DDT, l'échange avec Julien Lardermer sera l'occasion de repréciser "qui moissonne qui" avec Geo-IDE.


![Image](https://github.com/ecolabdata/ecospheres/assets/30289287/38816e6b-9561-4ec7-856d-77034265b405)

**Comment by alhyss** [comment]
> Concernant les organisations des DDT, l'échange avec Julien Lardermer sera l'occasion de repréciser "qui moissonne qui" avec Geo-IDE.

Pas de doute là-dessus. Géo-IDE ne sait pas moissonner d'autres catalogues. Si le même jeu de données est sur les deux, c'est forcément qu'il a été publié sur Géo-IDE puis moissonné par datARA.

Les [données de la Métropole de Lyon](https://catalogue.datara.gouv.fr/geonetwork/srv/fre/catalog.search#/search?facet.q=orgName%2FM%25C3%25A9tropole%2520de%2520Lyon&resultType=details&sortBy=relevance&fast=index&_content_type=json&from=1&to=20) sur dataARA sont toutes moissonnées depuis le [catalogue du Grand Lyon](https://data.grandlyon.com), et c'est la Métropole et pas la DREAL qui pourra décider si la manière dont [ses données](https://www.data.gouv.fr/fr/organizations/grand-lyon/#/datasets) remontent actuellement sur data.gouv.fr est satisfaisante. Même s'ils veulent expérimenter un moissonnage CSW/ISO, il pointera plus vraisemblablement sur leur catalogue que sur datARA.  

Par contre, il y a des DDT dont datARA est le catalogue primaire. La DREAL devrait pouvoir confirmer lesquelles et soit servir d'intermédiaire pour obtenir leur aval, soit nous mettre en contact.

**Comment by Thesauruv** [comment]
@alhyss merci pour ces précisions !

**Comment by streino** [comment]
Les endpoints GeoIDE devraient être en place d'ici le 18/3.

**Comment by streino** [comment]
Endpoints GeoIDE ARA + DGALN mis en place, sauf DDT69 (oubli, ne sera pas créé à temps).
Nous n'avons pas réussi à créer le endpoint DatARA. Je créerai un ticket pour tracker ça dès que possible (update : https://github.com/ecolabdata/ecospheres/issues/184).

**Comment by streino** [comment]
JDD des nouveaux moissonnages ajoutés au topic et remontent bien au search 👍
