### ISSUE TITLE
Bouquets "exemples" pour la release

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#107]
Proposition de bouquets : 
- Surchauffe urbaine ;
- Plantabilité des arbres ;

Préciser bouquet "exemple", sur la base de telles sources, etc.

**Comment by Thesauruv** [comment]
Bouquet sur la plantabilité actualisé : 
https://ecospheres.netlify.app/bouquets/plantabilite-des-arbres?fromSearch=1

Avec sa version Google Sheet lorsqu'il faudra le réintégrer dans la prod : 
https://docs.google.com/spreadsheets/d/1QaSNC4E0uNH4mQcWHBaL4Vf0G4pJqpTIAeqTAbPYX0A/edit#gid=0

**Comment by abulte** [comment]
A faire sur demo.ecologie.data.gouv.fr cf #113
