### ISSUE TITLE
Documentation FAQ

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#109]
Référence pour l'écriture de la doc : https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/cNT1D4gOhSZAjaxDuq8B/guide-utilisateur-rice/faq

Sections : 

- [x]  Guide de création de bouquets
- [x]  FAQ : Quel est le lien entre ecologie.data.gouv et data.gouv ?
- [x]  FAQ : Comment les organisations visibles depuis l'onglet données ont-elles été choisies ?
- [x]  FAQ : Comment publier un jeu de données sur ecologie.data.gouv ?
- [x]  FAQ : Je ne retrouve pas un jeu de données depuis ecologie.data.gouv ?
~~- FAQ : Quels mécanismes ont-été privilégiés pour le moissonnage des données géo ?~~

Faire le lien avec les objectifs France Nation Verte : 
https://www.gouvernement.fr/upload/media/content/0001/06/27899b60fe0cf622dc033d34bd8b2f1ab0c8102c.pdf

Question : besoin d'intégrer la roadmap, mais où ? Par exemple, une page sur les plateformes cibles à moissonner et l'état du moissonnage.

**Comment by streino** [comment]
Dépends de #110

**Comment by Thesauruv** [comment]
Dans [FAQ](https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/cNT1D4gOhSZAjaxDuq8B/guide-utilisateur-rice/faq), ajout des paragraphes : 
- Quel est le lien entre ecologie.data.gouv.fr et data.gouv.fr ?
- Quelles données sont accessibles depuis ecologie.data.gouv.fr ?

**Comment by DanFluture275** [comment]
Initialiser un doc de partage pour échange sur le contenu des différents items de la FAQ

**Comment by DanFluture275** [comment]
Contenu dispo pour review : https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/cNT1D4gOhSZAjaxDuq8B/guide-utilisateur-rice/faq
