### ISSUE TITLE
Conditions générales d'utilisation

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#112]
Il nous faut nos propres CGU pour ecologie.data.gouv.

- [ ] #180

[CGU ](https://www.francenum.gouv.fr/guides-et-conseils/developpement-commercial/site-web/rediger-des-conditions-generales-dutilisation) : 
- [x] Description des services 
- [x] Règles délimitant la responsabilité de l'éditeur

[Mentions légales](https://www.francenum.gouv.fr/guides-et-conseils/developpement-commercial/site-web/quelles-sont-les-mentions-legales-pour-un-site) : 
- [x] Pouvoir identifier le responsable du site
- [x] Informations relatives à l'hébergeur 
- [x] Informations sur l'éditeur
- [x] Informations relatives à l'utilisation des données personnelles et à la gestion des cookies

Validation par les services juridiques du MTE. Process : soumettre une saisine sur partaj.beta.gouv.fr avec une proposition de CGU.

Modèles : 
- https://www.data.gouv.fr/fr/terms/
- https://www.systeme-de-design.gouv.fr/a-propos/conditions-generales-d-utilisation
- https://gd4h.ecologie.gouv.fr/mentions-legales
- https://doc.transport.data.gouv.fr/le-point-d-acces-national/generalites/mentions-legales-et-conditions-generales-dutilisation

**Comment by Thesauruv** [comment]
A titre d'inspiration, le site du GD4H : 
https://gd4h.ecologie.gouv.fr/mentions-legales

**Comment by Thesauruv** [comment]
Outil pour la sollicitation de la DAJ : https://partaj.beta.gouv.fr/

**Comment by Thesauruv** [comment]
Exemple de saisine : https://partaj.beta.gouv.fr/app/my-dashboard/referral-detail/1081/content
Délai de traitement : 1.5 mois (en été...).

**Comment by Thesauruv** [comment]
Proposition de CGU et de mentions légales, sur la base des informations communiquées par data.gouv mais adaptées aux spécificités d'ecologie.data.gouv : [version drive](https://docs.google.com/document/d/14I2TBU_egA95bWX81bg6qNSTuXskKpTZEnpBLVeGAO8/edit).

Version Word : [CGU et Mentions Légales.docx](https://github.com/ecolabdata/ecospheres/files/14762762/CGU.et.Mentions.Legales.docx)

Besoin de reboucler sur : 
- La localisation des serveurs : est-on bien sur des serveurs OVH, en France ? Réponse : Oui.
- Disponibilité également à 99.5% ? Réponse : idem CGU data.gouv.
- Les CGU mentionnent Piwik comme outil d'analytique web, n'est-on pas sur Matomo ? Réponse : Matomo.
- Les données à caractère personnel : étant donné que l'inscription se fait depuis data.gouv, j'ai volontairement laissé les coordonnées de l'opérateur. Action : voir avec la DAJ
- J'ai supprimer le paragraphe "Transparence sur le classement et mise en avant", mais potentiellement besoin de le réintégrer. S'appuie-t-on aujourd'hui essentiellement sur le search de data.gouv pour la recherche de JDD ? Action : voir avec la DAJ.
- data.gouv a été déclarée à la CNIL, est-ce également un besoin de notre côté ? Action : voir avec la DAJ.

**Comment by Thesauruv** [comment]
@streino merci pour la relecture des CGU, je viens de répondre à tes commentaires. On peut partir sur cette base pour la publication et garder le ticket ouvert jusqu'au retour de la DAJ. Elles ont également été transmises à Geoffrey.

**Comment by streino** [comment]
Est-ce qu'on ferait pas un autre ticket pour la partie DAJ (une fois que [ta checklist est finie](https://github.com/ecolabdata/ecospheres/issues/112#issuecomment-2021154648)) ? Ca risque de trainer longtemps sur le backlog, je préférerais un truc du genre "Validation CGU DAJ", qu'on inclura dans aucune release.

**Comment by ecospheres** [comment]
@Thesauruv 

La [page des CGU actuelle](https://ecospheres.netlify.app/terms) contient :
```
## Copyright

- Illustrations de la page accueil : Freepik
```

On reprend ça où ?

**Comment by streino** [comment]
@Thesauruv

La [page des CGU actuelle](https://ecospheres.netlify.app/terms) contient :
```
## Copyright

- Illustrations de la page accueil : Freepik
```

On reprend ça où ?

**Comment by streino** [comment]
> On reprend ça où ?

Mis ici : https://github.com/opendatateam/udata-front-kit/blob/main/public/ecospheres/pages/terms.md?plain=1#L107

**Comment by streino** [comment]
Ticket pour suivi DAJ : https://github.com/ecolabdata/ecospheres/issues/180

**Comment by streino** [comment]
@Thesauruv je te laisse review [ta checklist](https://github.com/ecolabdata/ecospheres/issues/112#issuecomment-2021154648) et fermer en fonction.
