### ISSUE TITLE
Expérimentations autour des bouquets

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#12]
- [ ] Je cherche un bouquet
- [ ] Je crée un bouquet sur un sujet et une action imposé
- [ ] Je crée un bouquet sur un de mes sujets

**Comment by martyKN** [comment]
voir le protocole 
https://valentinlabit.notion.site/Tests-Utilisateurs-n-1-7481c165a7cd4ef8ab0af2be14cab034

**Comment by martyKN** [comment]
ah oui ca on peut close sans soucis. j'etais encore un noob sur github.

**Comment by streino** [comment]
:pray: 
Pour les prochaines fois, n'hésite pas à fermer le ticket toi-même dans ces cas là.
