### ISSUE TITLE
Page "Politique de confidentialité" dédiée

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#123]
Le lien "Politique de confidentialité" actuel renvoie vers la [page de data.gouv](https://www.data.gouv.fr/fr/suivi/).

@alhyss a suggéré qu'il pourrait être bien d'avoir notre propre page pour :
- Eviter de rediriger vers un autre domaine.
- Linker directement vers notre id matomo.

Le problème d'avoir notre propre page est qu'il faudra la garder synchrone avec celle de data.gouv car une large partie de notre politique de confidentialité dépend d'eux.

**Comment by streino** [comment]
Une solution serait d'avoir une page en propre qui indique simplement le "delta" avec les conditions de data.gouv (mention spécifiques à ecologie.data.gouv si elles existent + lien matomo), et redirige vers la page de data.gouv pour le reste.

Par contre, je ne sais pas si c'est acceptable de segmenter une telle page en deux ?

@alhyss @Thesauruv qu'en pensez-vous ?

**Comment by DanFluture275** [comment]
Won't do
