### ISSUE TITLE
Recommandations métadonnées ISO à destination des producteurs

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#124]
Rédiger des recommandations d'adaptation des métadonnées ISO 19139 pour faciliter la transformation en DCAT, à destination des producteurs/administrateurs de données.

https://pad.numerique.gouv.fr/FEVhnAL2R-6XSa_kIIMuJA

**Comment by streino** [comment]
Nouvel URL : https://ecospheres.gitbook.io/recommandations-iso-dcat

**Comment by streino** [comment]
Les préconisations initiales sont rédigées et plusieurs actions ont été lancées pour les mettre en place. Les améliorations futures feront l'objet de tickets séparés.

**Comment by maudetes** [comment]
Nouvelle URL : https://github.com/ecolabdata/ecospheres/wiki/Recommandations-ISO-DCAT
