### ISSUE TITLE
Pouvoir déplier/replier l'accordéon d'un bouquet en un clic

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#128]
Lorsqu'un utilisateur arrive sur la page d'un bouquet, l'accordéon est entièrement replié (ce qui est une bonne chose!). Néanmoins, il peut être utile de pouvoir le déplier en un clic afin de mettre en avant les labels qui ne sont pas associés à des jeux de données.

@martyKN @streino @abulte

**Comment by abulte** [comment]
> afin de mettre en avant les labels qui ne sont pas associés à des jeux de données

Du coup plus utile depuis #139 ?

**Comment by streino** [comment]
IMO ça reste utile. Amusez-vous à expand le bouquet "plantabilité" pour voir...
