### ISSUE TITLE
Obligations liées à la propriété intellectuelle

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#130]
Clarifier les obligations liées à la propriété intellectuelle pour ecologie.data.gouv.fr.
Par exemple, doit-on demander un consentement explicite à un créateur de bouquet ?
Y a-t-il d'autres contraintes ?

Lié à https://github.com/ecolabdata/ecospheres/issues/112

**Comment by abulte** [comment]
S'inspirer de data.gouv.fr là-dessus, qui n'impose aucune friction au moment de la publication et traite le cas dans les CGU.

**Comment by streino** [comment]
@Thesauruv je te l'assigne en rapport avec #112, ok ?

**Comment by Thesauruv** [comment]
Sujet traité dans le cadre des CGU. J'attends un retour de Geoffrey sur la première version avant envoi au service juridique.

**Comment by streino** [comment]
@Thesauruv on peut donc fermer ce ticket ?

**Comment by Thesauruv** [comment]
On peut fermer !
