### ISSUE TITLE
Avertissement de lancement en page d'accueil

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#131]
Pour ménager les attentes à l'ouverture, prévoir d'afficher/linker un court texte en page d'accueil pour préciser l'aspect "beta", le périmètre restreint et la démarche d'élargissement dans les mois à venir.

A coordonner :
- [x] Contenu du texte @Thesauruv @martyKN @streino 
- [x] Mise en place sur le site (e.g. encart page accueil, lien vers page de doc dédiée, ...) @martyKN @abulte #136

**Comment by martyKN** [comment]
en regardant les sites de beta.gouv, j'ai vu des tags dans le header sous ou a côté du nom du produit avec "beta" ou "en construction"
<img width="511" alt="Capture d’écran 2024-03-11 à 10 49 47" src="https://github.com/ecolabdata/ecospheres/assets/74351881/d502f4ec-bd8b-4f0a-8b66-b067cebe2f00">
<img width="638" alt="Capture d’écran 2024-03-11 à 10 49 42" src="https://github.com/ecolabdata/ecospheres/assets/74351881/9ace230b-58fe-4e87-9160-47a3f09d2071">

**Comment by streino** [comment]
On a déjà le tag "beta" :v: 
L'idée était d'avoir quelque chose plus explicite. Surtout au niveau données/bouquets vu qu'on va commencer avec pas grand chose.

**Comment by abulte** [comment]
Intégration via la config d'un [bandeau d'information importante](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bandeau-d-information-importante) avec un texte configurable et un lien vers une page explicative.

**Comment by streino** [comment]
@Thesauruv Le texte est défini ici : https://github.com/opendatateam/udata-front-kit/blob/main/configs/ecospheres/config.yaml#L58
