### ISSUE TITLE
Filtrer les bouquets par couverture spatiale

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#134]
Sur la page de liste des bouquets, ajouter les filtres :
- ~~Granularité spatiale~~
- Couverture spatiale

Cf #74 pour le support des champs associés sur un bouquet.

Implémentations possibles :
- même mécanisme que thème / sous thèmes : on charge tous les bouquets et on filtre la liste en local
- ou voir si possible d'utiliser des filtres (à implémenter) côté data.gouv.fr pour ne pas forcément charger tous les bouquets (passe mieux à l'échelle, pas utile à court terme AMHA)
- idéalement, avoir des facettes sur les bouquets côté data.gouv.fr (longue haleine)

<img width="234" alt="Capture d’écran 2024-03-11 à 11 48 31" src="https://github.com/ecolabdata/ecospheres/assets/119625/7e483b50-56c0-4e5a-af4a-51f4cc17e936">

**Comment by streino** [comment]
Dépends de #74 et champs+filtres spatiaux sur les topics côté data.gouv.

**Comment by Thesauruv** [comment]
Pour la granularité, à mûrir, ticket à redécouper.
