### ISSUE TITLE
gestion du markdown

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#137]
quand je crée un bouquet et que je met un titre en markdown (#) il apparait bien plus gros que le titre "objectif du bouquet" qui est la par défaut. Je suis obligé de passé au sousous titre (###) pour avoir un titre plus ou moins équivalent en taille au titre qui est la par défaut (objectif du bouquet) 
Question = est il possible de gérer les tailles du markdown et de faire en sort que quand je met un titre (#) ca fasse un titre de la taille du titre présent par défaut (objectif du bouquet)

**Comment by abulte** [comment]
C'est le cas depuis #91, on utilise le composant data.gouv.fr qui gère ça

C'est pas encore parfait mais... https://ecospheres-dev--ecospheres.netlify.app/bouquets/bouquet-alb-avec-un-titre-vachement-long-comme-le-font-les-usagers

**Comment by abulte** [comment]
Sur la branche principale maintenant https://ecospheres.netlify.app/bouquets/bouquet-alb-avec-un-titre-vachement-long-comme-le-font-les-usagers

**Comment by martyKN** [comment]
c'est de la faute des usagers

**Comment by streino** [comment]
Lié à https://github.com/opendatateam/udata-front-kit/issues/149
On considère qu'on est bon ou faut pousser plus loin @martyKN ?

**Comment by martyKN** [comment]
c'est pas déployé sur demo on est d'accord? je viens de faire le test sur netlify et c'est ok pour moi.
Est ce que à terme on pourrait dans le champ texte montrer une preview de ce que rend le markdown quand je suis toujours en mode edition ?

**Comment by abulte** [comment]
Ce n'est pas sur demo.ecologie.data.gouv.fr en effet.

Oui on peut voir pour intégrer un éditeur style GitHub.

**Comment by streino** [comment]
On est ok avec ce qu'on a pour l'instant -> close
