### ISSUE TITLE
Afficher le tag de disponibilité dans le titre des jeux de données d'un bouquet

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#139]
Exemple :

<img src="https://github.com/opendatateam/udata-front-kit/assets/30210525/214b5388-7023-477e-a0c6-e7fceef8a6f0" width=600/>

_Cf https://github.com/opendatateam/udata-front-kit/pull/370#discussion_r1521509343_

**Comment by Thesauruv** [comment]
et privilégier une couleur plutôt dans le rouge pour attirer davantage l'attention que le gris actuel

**Comment by streino** [comment]
Je n'ai pas priorisé pour l'instant, à voir par rapport aux autres "nice to have".
