### ISSUE TITLE
Intégrer la vue par onglet dans les bouquets

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#140]
Même chose que pour les jeux de données : 

![image](https://github.com/ecolabdata/ecospheres/assets/30210525/e4738938-c5b9-4afe-99d0-aaa25c9625f6)

Dans un premier temps, mettre les onglets suivants : 
- Données
- Discussions 

@martyKN ok avec ça ?

**Comment by martyKN** [comment]
ouii! => pas besoin d'onglet reglementation je pense à ce stade
![image](https://github.com/ecolabdata/ecospheres/assets/74351881/ffab826d-597b-43e3-a8e8-7c17f3b0d6d8)
