### ISSUE TITLE
Simplifier le parcours de publication

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#141]
@martyKN [figma ](https://www.figma.com/files/project/73963494/Ecosph%C3%A8res?fuid=1155057458268856683)du parcours utilisateur (à préciser)

**Comment by streino** [comment]
Considérer aussi #144

**Comment by martyKN** [comment]
https://www.figma.com/file/YmsbJVui0zKVAHNx9NPFAA/Bouquets?type=design&node-id=3648%3A26129&mode=design&t=IHhJlG70qHqNnfOa-1 
Un option qui mèle B et D semble pas mal -> Une one page pour l'edition du bouquet et un tunnel pour l'ajout d'un jdd

**Comment by streino** [comment]
Restent des questions sur l'articulation des points de sauvegarde dans le parcours de création/édition et de l'état de publication.

Le design actuel fait que les auto-save vont être directement visibles online pour les bouquets publiés. Pour un bouquet publié il faudrait alors conserver un état "brouillon" lors des éditions en plus de la version publiée. Si on veut que cet état "brouillon" survive une fermeture/crash navigateur, il faut qu'il soit stocké en back via l'API. Donc deux objets "topic" pour un même bouquet. Pas simple à gérer, sauf à avoir une fonctionnalité de versioning côté data.gouv (qui n'existe pas).

Toujours sur l'auto-save, la question se pose de leur déclenchement. A chaque frappe ? A chaque changement de focus ? Toutes les x secondes/minutes ? Dans tous les cas, le résultat risque d'être bizarre si le bouquet est publié et que les modifications sont visibles de tous.

On a réfléchi avec @abulte à une option E qui simplifie le parcours et devrait couvrir correctement les points de sauvegarde et l'état de publication. Les points principaux sont : 
- Focus majeurs : simplicité d'usage et simplicité d'implémentation, dans cet ordre.
- La vue "finale" du bouquet sert de pivot pour toutes les actions d'éditions, plutôt qu'une vue "preview" séparée.
- Chaque type de modification est "atomique" dans le sens où il modifie une partie cohérente du bouquet sans embarquer d'autres modifications qui rendraient la vue "finale" du bouquet instable.
- Toutes les modifications doivent être validées manuellement. Plus d'auto-save, et donc plus de questions sur quand le déclencher.
- Reprend globalement le fonctionnement data.gouv ([cf figma](https://www.figma.com/file/blyUlzTBvBwl31CWebJ19T/Cr%C3%A9ation-bouquets---Option-E?type=design&node-id=10-100&mode=design&t=9Vayh8fErk4yc9og-4)), à ceci près qu'il n'y a pas d'écran "preview" pivot (pas utile à ce stade car pas de fonction d'admin autres que les fonctions basiques d'édition).

Vu mes compétences de n00b en figma, J'ai préféré faire un doc séparé pour pas vous casser vos designs : 
https://www.figma.com/file/blyUlzTBvBwl31CWebJ19T/Cr%C3%A9ation-bouquets---Option-E
Si on juge l'option valable, je m'en remets à @martyKN et Alexandra pour reprendre proprement la proposition dans le figma officiel.

@martyKN un retour côté design ?
@Thesauruv un retour côté usage ?

**Comment by martyKN** [comment]
le design va etre repris demain par Alexandra, on y verra plus clair si y'a des coquilles mais ca a l'air propre
