### ISSUE TITLE
Ajouter à mon bouquet

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#144]
Permettre d'ajouter un jeu de données à un bouquet depuis une page jeu de données.

**Comment by streino** [comment]
Quelques questions à clarifier : 
- Complémentaire ou en remplacement du parcours de création de bouquet ?
- Ajout dans un seul bouquet "en cours" (type cart) ou la possibilité de sélectionner à chaque ajout le bouquet ciblé
- Renvoi vers la page d'édition de bouquet ou modal ou ...

**Comment by abulte** [comment]
Je verrais bien :
- clic "Ajouter à un bouquet" sur un jeu de données
- ouverture modale avec 
  - liste déroulante de mes bouquets, triés par last_modified DESC
  - champs texte "Libellé de la donnée" (pré rempli avec le titre du jeu de données ?) et "Raison d'utilisation dans ce bouquet"
  - bouton valider, sauvegarde dans le bouquet et ferme la modale
  
Plutôt complémentaire donc. J'aurais tendance d'une manière générale à séparer la gestion des métadonnées du bouquet et des jeux de données dedans.

**Comment by martyKN** [comment]
> Je verrais bien :
> 
> * clic "Ajouter à un bouquet" sur un jeu de données
> * ouverture modale avec
>   
>   * liste déroulante de mes bouquets, triés par last_modified DESC
>   * champs texte "Libellé de la donnée" (pré rempli avec le titre du jeu de données ?) et "Raison d'utilisation dans ce bouquet"
>   * bouton valider, sauvegarde dans le bouquet et ferme la modale
> 
> Plutôt complémentaire donc. J'aurais tendance d'une manière générale à séparer la gestion des métadonnées du bouquet et des jeux de données dedans.

d'accord avec ca
