### ISSUE TITLE
Parcours de création : search ecologie.datagouv

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#147]
Dans le parcours de création, quand je recherche un jdd via ecologie.data.gouv.fr, je n'ai pas toutes les infos sur les données qui me sont proposées. J'ai du mal à faire mon choix car plusieurs jdd peuvent avoir le meme nom, je n'ai pas d'indice sur la zone géo concernée
Je n'ai pas de solution au problème que je soulève ;)

**Comment by streino** [comment]
Alternative fonctionnelle : https://github.com/ecolabdata/ecospheres/issues/144

**Comment by Thesauruv** [comment]
A moyen terme, l'outil de gestion de patrimoine facilitera la recherche. En attendant, je lie ce ticket à celui sur l'export des métadonnées des JDD remontés dans le catalogue : https://github.com/ecolabdata/ecospheres/issues/153

**Comment by streino** [comment]
Voir si c'est toujours pertinent après https://github.com/ecolabdata/ecospheres/issues/141

**Comment by streino** [comment]
@martyKN tjs pertinent avec l'affichage des cartes ? On a pas la geozone mais on a d'autres infos qui devraient permettre de désambiguer dans bcp de cas.

**Comment by martyKN** [comment]
on a les infos necessaires, on peut close !
