### ISSUE TITLE
Présentation d'un bouquet

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#148]
J'arrive sur un bouquet, je vais voir les données liés au bouquet. Je souhaite en un coup d'oeil voir les données dispo (et du coup cataloguées) des données non disponibles. 
Est ce possible d'ajouter un tag "donnée non disponible" sur l'accordéon.
=> il me semble qu'il y a déjà un ticket pour ca, mais je sais pas trop où et comment le retrouver @streino 
<img width="660" alt="Capture d’écran 2024-03-14 à 09 58 24" src="https://github.com/ecolabdata/ecospheres/assets/74351881/c506ed52-9845-4acb-8327-45a09bd511c4">

**Comment by abulte** [comment]
Done #139
