### ISSUE TITLE
Parcours de création : positionnement des champs URL et search à l'ajout d'un jeu de données

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#149]
Quand je recherche une données via ecologie.dgfr ou quand je souhaite coller une url dans le but d'ajouter un jdd à mon bouquet, les champs s'affichent en bas de la page.
Il est possible que nos users loupe le champ. 
De mon point de vue, je mettrai le champ de remplissage d'url et de search jsute en dessous du choix par bouton radio.

1- je clique sur le bouton radio ecologie.data.gouv.fr
2- s'affiche juste en dessous la barre de search et ce décale vers le bas les autres boutons radios
(même déroulé pour l'ajout d'une url)

**Comment by streino** [comment]
Il semble que c'est pas prévu dans le composant DSFR.
J'ai une préférence pour rester sur le comportement standard, ne serait-ce qu'au point de vue RGAA.

**Comment by streino** [comment]
Voir si c'est toujours pertinent après https://github.com/ecolabdata/ecospheres/issues/141

**Comment by streino** [comment]
@martyKN tjs pertinent ?

**Comment by martyKN** [comment]
on peut close.
