### ISSUE TITLE
Eviter de refaire tout le parcours d'édition lorsqu'on édite une seule section

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#151]
Lorsque je souhaite éditer un élément dans un bouquet, l'objectif par exemple.
1- je clique sur le crayon
2- je fais ma modification
3- je valide
4-je retourne à l'etape 1 de création du bouquet

L'etape 4 me semble bizarre, d'après moi il serait plus pertinent de revenir à le fenetre d'edition du bouquet en format récapitulatif (Récapitulatif du bouquet de données Étape 4 sur 4)

**Comment by abulte** [comment]
4 - Tu vas à l'étape 2 plutôt ?

Je vois le problème, mais comment garder la cohérence avec le stepper ? Ici on aurait un "Suivant" qui fait étape courante + 3.

**Comment by streino** [comment]
Sauf s'il y a un quickfix, je pense qu'on ferait mieux de se focaliser sur https://github.com/ecolabdata/ecospheres/issues/141

**Comment by martyKN** [comment]
> 4 - Tu vas à l'étape 2 plutôt ?
> 
> Je vois le problème, mais comment garder la cohérence avec le stepper ? Ici on aurait un "Suivant" qui fait étape courante + 3.

oui pardon étape 2

**Comment by streino** [comment]
Wontdo, a considérer dans le contexte de #141
