### ISSUE TITLE
Permettre un export des métadonnées des JDD dans le contexte d'un bouquet

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#152]
En attendant d'avoir un couplage plus dynamique avec un outil datavisualisation, il est utile d'offrir un export des métadonnées des jeux de données dans le contexte du bouquet.

Il s'agirait d'exporter les informations suivantes : 
- la label
- la description du label
- l'URI du JDD
- le titre du JDD
- la date de modification du JDD
- l'organisation rattachée au JDD
- autres métadonnées si facilement accessibles (point de contact, localisation, etc.)

Depuis la version actuelle des bouquets, il n'est pas possible de visualiser rapidement ces informations sans cliquer sur chacune des fiches de métadonnées des JDD. J'ai dû me faire un fichier excel à part. Même chose du côté du projet des indicateurs territoriaux.

Exemple sur le bouquet sur la plantabiltié ([lien vers la Google Sheet](https://docs.google.com/spreadsheets/d/1QaSNC4E0uNH4mQcWHBaL4Vf0G4pJqpTIAeqTAbPYX0A/edit#gid=0))
![image](https://github.com/ecolabdata/ecospheres/assets/30289287/23eef4f2-9999-4905-bbfe-1398fee22b09)

**Comment by streino** [comment]
Voir avec data.gouv si on peut faire une route d'export csv sur les topics

**Comment by Thesauruv** [comment]
Prio sur le moissonnage.

**Comment by abulte** [comment]
@maudetes ça vous irait si je fais une route `/topics/{id}/datasets.csv`, façon [organization](https://github.com/etalab/udata-front/blob/1cc30c449082aa22fe2bafe4cc46c268c31fa797/udata_front/views/organization.py#L119) pour traiter ça ?

**Comment by maudetes** [comment]
A voir s'il y a des limitations (notamment à cause de la taille du topic, etc.), mais il est déjà possible de filtrer sur les topics sur l'endpoint `datasets.csv` général.
Ex: https://www.data.gouv.fr/fr/datasets.csv?topic=65b76b8536f029909a82ca1c

**Comment by abulte** [comment]
Ah trop bien 💡 🙏
