### ISSUE TITLE
Export des métadonnées des jeux de données remontées dans ecologie.data.gouv

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#153]
A l'image du fichier **export-resource-20240314-055324.csv** disponible depuis la page [Catalogue des données de data.gouv](https://www.data.gouv.fr/fr/datasets/catalogue-des-donnees-de-data-gouv-fr/), permettre un export csv des données remontées dans ecologie.data.gouv.

**Comment by streino** [comment]
@abulte Tu sais comment ça fonctionne côté data.gouv j'imagine.
On pourrait leur demander d'ajouter un export pour nous ?

**Comment by abulte** [comment]
C'est faisable mais c'est hyper-spécifique Ecosphères quand même

**Comment by streino** [comment]
Ca pourrait être un export par topic univers. Mais on risque en effet d'être les seuls pendant un certain temps...

**Comment by abulte** [comment]
Voir https://github.com/ecolabdata/ecospheres/issues/152#issuecomment-2029762268, si le topic n'est pas trop gros on pourra utiliser cet endpoint sur le topic univers.
