### ISSUE TITLE
Abonnement à un bouquet

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#155]
En tant que collaborateur sur un bouquet, je souhaite pouvoir suivre un bouquet et être informé de toute évolution : 
- ajout ou modification d'une métadonnée du bouquet (titre, description, label, description du label, donnée manquante, etc.)
- actualisation d'une métadonnée d'un jeu de donnée

**Comment by streino** [comment]
Doublon de #73
