### ISSUE TITLE
Supprimer le bouton "revenir aux résultats"

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#157]
Le bouton "revenir aux résultats" n'est pas correctement aligné : 

![image](https://github.com/ecolabdata/ecospheres/assets/30210525/9f56b525-827a-4311-9f65-33eec7c68071)

L'autre solution est de le virer. @martyKN ?

**Comment by martyKN** [comment]
si on vire, on est d'accord que le fil d'ariane produit le meme effet ?si oui ok pour virer

**Comment by abulte** [comment]
Oui, il faudrait juste rajouter "Bouquets" dans le fil pour être complet

**Comment by streino** [comment]
Le bouton "revenir aux résultats" est équivalent au "back" du navigateur.
Mais tu peux en effet arriver au même endroit selon où tu cliques sur le fil d'ariane.

> il faudrait juste rajouter "Bouquets" dans le fil pour être complet

It is in fact a bug: https://github.com/ecolabdata/ecospheres/issues/158
