### ISSUE TITLE
Utiliser des tiles data.gouv dans la liste de données d'un bouquet

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#159]
Ca permettrait d'harmoniser la liste des données d'un bouquet avec la liste de l'onglet Données.

Voir déjà si on est ok avec l'idée côté design @martyKN 

Puis besoin de clarifier comment ça se passe avec : 
- les liens hors data.gouv, on aura pas les MD
- les données manquantes

**Comment by martyKN** [comment]
je pense aussi au besoin de clarifier un truc qui est : 

- qu'est ce qu'on fait du libellé renseigné par l'utilisateur•rice ? 
- qu'est ce qu'on fait de la description renseignée par l'utilisateur•rice

=> les tuiles présente le titre qui est sur dgfr ainsi que quelques MD

**Comment by Thesauruv** [comment]
Les libellé m'apparaissent essentiels dans la logique de territorialisation. Je projette notamment que les libellés soient conservés d'un territoire à un autre, comme dénominateur commun du cas d'usage : les problèmes ont les mêmes variables (ou facteurs/indicateurs/libellés), mais des données produites différemment. 

Si on prend le bouquet sur la plantabilité, l'indicateur de plantabilité intègre la localisation des réseaux de fibre optique. A la métropole de Lyon, le JDD s'appelle "Réseau d'Initiative Publique la fibre Grand Lyon", à Rennes il correspond à "Fibre optique Rennes Métropole : conduites / infrastructure". Dans le cas des indicateurs territoriaux, on voit qu'un même JDD peut contenir plusieurs indicateurs intéressants, dans les bouquets il sera pertinent de référencer individuellement chaque indicateur quitte à renvoyer vers le même JDD.

Maintenant, d'un point du vue design, la question se pose : a-t-on toujours besoin d'un distingo par rapport au nom du JDD ? Je penche pour cette option, les libellés doivent être les plus stables possibles et pour la majorité des jeux de données territoriaux il n'existe pas encore de base de donnée nationale les agrégeant. Par contre, si un JDD existe, je pense qu'on devrait afficher dans la liste des bouquets quelques informations telles que le nom du JDD, la date de modif et l'organisation.

**Comment by Thesauruv** [comment]
J'ai dû mal à voir à quoi ressemblerait l'introduction des tiles, les libellés de données seraient-ils écartés ?

**Comment by streino** [comment]
Vu avec @Thesauruv l'idée est de garder l'accordéon tel quel et remplacer le bouton "Accéder au catalogue" par la tile du dataset lorsque c'est un lien data.gouv.

```
Réseau de gaz                                      +
Lignes électriques aériennes basse tension         -
 Tracés des lignes électriques aériennes...
 ------------------------------------------
 |  tile                                  |
 ------------------------------------------
Reseau d'eau potable             <non disponible>  +
Pistes cyclables                                   -
 Objet linéaire décrivant une infrastructure...
 [Accéder au catalogue externe]
```

Alexandra a un truc qui ressemble dans la refonte du parcours de création : https://www.figma.com/file/YmsbJVui0zKVAHNx9NPFAA/Bouquets?type=design&node-id=3677-220005&mode=design&t=Q8vsQHfsijl0DsvH-4

@abulte c'est faisable sans trop de bidouille ?

**Comment by abulte** [comment]
Techniquement ça devrait aller, graphiquement ça va faire un peu chargé je pense. Mais on peut tenter.

**Comment by streino** [comment]
@martyKN je recopie ici le screenshot de la PR. Pour moi c'est ok tel quel pour la release, mais il y a peut-être un peu de styling à faire pour rendre le truc plus lisible ?

<img width="1269" alt="Capture d’écran 2024-04-01 à 12 39 11" src="https://github.com/opendatateam/udata-front-kit/assets/119625/fe124905-e658-4fd1-a297-c7b796d681cb">

**Comment by martyKN** [comment]
Essayons comme ca, mais j'émets une grosse reserve quand certaines personnes vont raconter leur vie dans la description. 
La ca fait : 
Titre 
texte 
titre 
sous titre 
texte
et ca fait beaucoup :)
la comme ca j'ai pas de solution miracle. Peut etre que le regroupement des données par thématiques dans un bouquet pourrait rendre plus lisible l'affaire

**Comment by streino** [comment]
Pour moi il y a des trucs à faire, genre : 
- Limiter la taille des sous-textes affichés, avec par exemple la possibilité d'expand le-dit texte.
- Jouer sur les tailles de police des titres et/ou backgrounds (comme ça a été fait sur la home avec l'alternance fond blanc/gris qui délimite bien les sections).
- Simplifier la tile de jeu de données pour n'afficher que ce qu'on considère essentiel (ça nécessitera sans doute de retourcher le composant côté data.gouv, donc pas forcément la première option à explorer).
