### ISSUE TITLE
Ajouter des filtres à l'API des topics data.gouv.fr 

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#164]
Afin de :
- gérer #134 
- permettre de récupérer les bouquets d'un utilisateur ou d'une organisation depuis le serveur (e.g. #144)
- permettre de filtrer les brouillons depuis le serveur

Il est nécessaire d'ajouter les filtres suivants à l'API des topics de data.gouv.fr :
- spatial.zone
- spatial.granularity
- organization
- owner
- private

Cela nous permettrait de basculer l'intégralité des filtres sur l'API plutôt que de récupérer la liste complète des bouquets et la filtrer en local (meilleure passage à l'échelle et moins de dette technique).

Le parser de requête étant mutualisé entre les API v1 et v2, les filtres seront disponibles sur les deux endpoints.

Pour `private` : idéalement, se comporterait comme un toggle "Inclure les brouillons oui / non" plutôt que récupérer seulement les private ou tout sauf les private. Mais voir cohérence avec le reste de l'API data.gouv.fr.

**Comment by abulte** [comment]
@maudetes ça vous irait comme contribution ?

**Comment by maudetes** [comment]
Oui, très preneurs de cette contribution :)

Pour le private, en effet il y a le risque que ça manque de cohérence avec le reste de data.gouv.fr comme comportement cc @agarrone

**Comment by agarrone** [comment]
On a pas de comportement dans le front pour les private. Ce n'est pas recherchable. Je pense qu'il faut que se pose la question sur ce comportement avec le catalogage notamment.
