### ISSUE TITLE
Attribution freepik sur les illustrations

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#165]
> peut etre faut il mentionner "freepik" sous l'illustration. Les personnages viennent de freepik, mais l'illu globale a été réalisée par Alexandra.

_Originally posted by @martyKN in https://github.com/opendatateam/udata-front-kit/issues/375#issuecomment-1997164009_

Si nécessaire, inclure les mentions directement dans les svg :pray:

**Comment by martyKN** [comment]
done

**Comment by abulte** [comment]
@martyKN A mettre sur les deux illustrations, non ? Par exemple si on réutilise l'image ailleurs, ça éviter d'oublier. Sinon, quitte à le mettre qu'une fois, on peut le mettre dans les mentions légales :-)

**Comment by martyKN** [comment]
Il y'a juste les 2 perso qui sont récupérés de freepik, donc pas besoin sur l'autre illu. Mais en effet, juste mettre les crédits freepik dans les mentions légales suffisent et n'ont du coup pas besoin d'apparaitre sur la home

**Comment by martyKN** [comment]
erratum, on me dit dans l'oreillette que la main de la deuxième illu provient de freepik. Donc mettre les credits freepik dans les mentions légales. Désolé pour les A/R

**Comment by martyKN** [comment]
Oui, je viens de voir que la main de la seconde illu etait freepik. Du coup mettre dans les mentions legales 
"Copyright
Illustrations de la page accueil : Freepik"

**Comment by streino** [comment]
Fixed https://github.com/opendatateam/udata-front-kit/pull/386
