### ISSUE TITLE
Tri de la liste des bouquets

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#168]
Permettre de trier la liste des bouquets par :
- Titre
- Date de création
- Date de modification

Quel serait le tri par défaut @streino @martyKN ?

Cf #133

**Comment by martyKN** [comment]
je vote pour création !
et j'appui mon vote d'un argumentaire : comme ca on a pas toujours le meme bouquet en 1ere page (celui qui commence par A)
et je mettrais pas par modification car un mini changement sur un bouquet (ajout d'une virgule) ferait remonter le bouquet tout en haut de la liste. DONC CREATION POUR MOI

**Comment by streino** [comment]
Ok pour moi
