### ISSUE TITLE
Restreindre la suggestion de géozone au territoire français

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#172]
>>> Possible de limiter aux territoires français ?
>>> ![world](https://github.com/opendatateam/udata-front-kit/assets/30210525/793a0976-be79-4706-a403-59195cd7d2cf)

>> Non je ne pense pas.

> -> later

_Cf https://github.com/opendatateam/udata-front-kit/pull/393#pullrequestreview-1951630775_

**Comment by abulte** [comment]
Est-ce vraiment gênant et/ou inutile ?

Dans le cas gênant, quelle requête "légitime" sur le territoire français remonte suffisamment de résultats mondiaux pour que la liste soit vraiment polluée ?

Dans le cas inutile, n'y-a-t-il pas des données disponibles pour > ou ailleurs que la France ? L'écologie est un sujet global et transfrontalier s'il en est. E.g. la fonte des glaces des pôles ou des données espagnoles quand je travaille sur les Pyrénées.

**Comment by streino** [comment]
Sur une requête complète je pense que ça ne pose pas de problème, par contre sur le début du suggest (qqs caractères) ça pollue pas mal je trouve (par ex les requêtes "bou" pour bourgogne, ou "nord"). Et donc ça réduit l'efficacité du suggest, car il faut taper un peu plus pour reduire la liste.

Je suis d'accord avec toi sur la pertinence dans certains cas des _données_ au delà du territoire français, mais : 
- Est-ce que ces données seront sur data.gouv._fr_ ?
- Est-ce qu'on prévoit de faire des bouquets hors fr sur ecologie.data.gouv._fr_ ?

En imaginant que les bouquets dépassent les frontières on pourra étendre le périmètre (et changer de domain ?), mais pour l'instant tout ce qui est hors fr ne me paraît pas très pertinent.

**Comment by streino** [comment]
Est-ce qu'il ne faudrait pas carrément limiter les suggestions aux quelques niveaux auxquels on envisage de faire des bouquets ? À l'opposé des pays étrangers, est-ce qu'on veut pouvoir faire des bouquets au niveau des arrondissements de villes ? Tous ces résultats ramènent du bruit et rendent plus difficile le choix de la zone spatiale utile.

Peut-être faudrait-il afficher que les résultats qui ont déjà des bouquets, si toutefois c'est jouable... ? On perd le "Il n'y a pas encore de bouquet sur ce thème" mais on gagne en lisibilité des suggestions.

**Comment by DanFluture275** [comment]
Won't do
