### ISSUE TITLE
Présentation des métadonnées dans l'onglet "Informations"

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#174]
Exemple à partir de la fiche de métadonnées : [Infrastructures de réseau de gaz](https://ecospheres.netlify.app/datasets/62e1fc65d2d57106c20505d1)

Observation 1 : erreur de label pour la couverture spatiale 
![image](https://github.com/ecolabdata/ecospheres/assets/30289287/c2afc54c-a8de-43da-83cb-288a3304f578)

Observation 2 : impossible scroller sur l'ensemble des extras (test depuis l'écran d'un ordinateur portable.

![image](https://github.com/ecolabdata/ecospheres/assets/30289287/de0e0f0b-de3d-4eaa-8d73-11e13ec97806)

**Comment by streino** [comment]
Observation 1 -> https://github.com/opendatateam/udata-front-kit/issues/398

Observation 2 -> https://github.com/opendatateam/udata-front-kit/issues/342

**Comment by streino** [comment]
@Thesauruv de préférence, faire un ticket par dysfonctionnement :pray:
