### ISSUE TITLE
Description du bouquet - Texte d'aide à l'utilisateur

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#178]
@martyKN Je propose de remplacer l'actuel texte d'aide à l'utilisateur (voir screenshot ci-dessous) par le suivant afin de coller aux recommandations du guide utilisateur : 

_Renseigner ici les informations nécessaires à la compréhension du bouquet :  politique publique et problématique à laquelle il répond, lien vers toute méthodologie de traitement des données, description de l'organisme porteur du projet, etc._

![image](https://github.com/ecolabdata/ecospheres/assets/30289287/433d7196-0ba4-48b0-8d33-348e4e46b35b)

**Comment by martyKN** [comment]
y'a cette partie ***problématique d'aide à la décision à laquelle il répond*** qui je pense n'est pas claire
*Renseigner ici les informations nécessaires à la compréhension du bouquet : politique publique et problématique ~~d'aide à la décision~~ à laquelle il répond, lien vers toute méthodologie de traitement des données, description de l'organisme porteur du projet, etc.*

**Comment by Thesauruv** [comment]
Ok, je prends. @martyKN c'est actualisé, merci pour le retour.

**Comment by streino** [comment]
Il y a une modif à faire côté code ? Si oui, c'est quoi le texte final ?

**Comment by abulte** [comment]
@streino je prends, ça me parait clair
