### ISSUE TITLE
Tooltip "Raison d'utilisation dans ce bouquet"

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#179]
L'actuel tooltip (voir screenshot ci-dessous) renvoie au texte support pour la description du bouquet et non à la raison d'utilisation du jeu de données. Je propose le texte suivant : 

_Renseignez la raison d'utilisation de cette information si celle-ci n'est pas évidente. Vous pouvez également utiliser cet espace pour renseigner des problèmes liés l'accès ou la qualité des données._

![image](https://github.com/ecolabdata/ecospheres/assets/30289287/26a87292-7567-45bf-b716-0ab232d55fff)

@martyKN

**Comment by martyKN** [comment]
exact, tu as raison, ok pour le texte ping @abulte 
j'update dans le figma
