### ISSUE TITLE
Review DAJ des CGU et Mentions légales

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#180]
https://partaj.beta.gouv.fr/

Points particulier à voir avec la DAJ : 
- [ ] Les données à caractère personnel : étant donné que l'inscription se fait depuis data.gouv, laisser les coordonnées de l'opérateur. 
- [ ] J'ai supprimer le paragraphe "Transparence sur le classement et mise en avant", mais potentiellement besoin de le réintégrer. 
- [ ] data.gouv a été déclarée à la CNIL, est-ce également un besoin de notre côté ?
- [ ] Version GitBook : coquille à corriger dans le paragraphe "Publication et commentaires" : _contreviendrait > contreviendraient_ (je n'ai pu éditer la page avec le compte Ecosphères)

**Comment by Thesauruv** [comment]
Saisine transmise à la DAJ (15/05/2024).

**Comment by Thesauruv** [comment]
En copie, le document word reprenant les commentaires de la DAJ.
[CGU_et_Mentions_Légales_-_ecologie.data.gouv_vuAJAG2.docx](https://github.com/user-attachments/files/16081760/CGU_et_Mentions_Legales_-_ecologie.data.gouv_vuAJAG2.docx)

**Comment by Thesauruv** [comment]
Fermeture de ce ticket, création d'un nouveau ticket pour l'intégration des commentaires de la DAJ : https://github.com/ecolabdata/ecospheres/issues/286
