### ISSUE TITLE
Reprendre le warning score métadonnées de data.gouv

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#187]
![image](https://github.com/ecolabdata/ecospheres/assets/30210525/0fc07df8-6a14-488b-a07d-3c93387e12c6)

**Comment by streino** [comment]
Dépend de la mise à jour du composant data.gouv

**Comment by streino** [comment]
@nicolaskempf57 je crois avoir déjà demandé mais je ne retrouve plus notre discussion.
Le warning c'est quelque chose qui peut être intégré dans data.gouv.fr-components assez rapidement, ou c'est à faire de notre côté ?

**Comment by nicolaskempf57** [comment]
> @nicolaskempf57 je crois avoir déjà demandé mais je ne retrouve plus notre discussion. Le warning c'est quelque chose qui peut être intégré dans data.gouv.fr-components assez rapidement, ou c'est à faire de notre côté ?

Je pense que le plus simple est effectivement de le reprendre sur udata-front-kit comme il s'agit d'un composant que nous n'utiliserons pas sur udata-front. Cela permet de simplifier sa configuration par rapport à l'avoir dans data.gouv.fr-components.

**Comment by streino** [comment]
On a besoin de toi @nicolaskempf57 pour adopter le composant ou @abulte peut s'en charger ?

**Comment by nicolaskempf57** [comment]
> On a besoin de toi @nicolaskempf57 pour adopter le composant ou @abulte peut s'en charger ?

En soit la logique est juste un [check des métadonnées](https://github.com/datagouv/udata-front/blob/master/udata_front/theme/gouvfr/templates/macros/quality_score_with_warning_below.html#L6). Il faudra par contre reprendre dans udata-front-kit la liste des back-ends à ignorer.

On a la même logique sur les cartes d'un jeu de données, ce point est [en cours de dev](https://github.com/datagouv/udata-front/pull/397) pour que ce soit repris dans la carte dataset du package data.gouv.fr-components.

**Comment by abulte** [comment]
Ce qui est fait sur data.gouv.fr :

Si le jeu de données est moissonné via `CSW-ISO-19139`, le détail des problèmes de qualité (Documentation des fichiers manquante...) est remplacé par l'avertissement. La barre de progression reste visible.

Veut-on faire strictement la même chose ? @streino @Thesauruv

**Comment by Thesauruv** [comment]
@abulte le message d'avertissement permet de nuancer l'indication sur la qualité des métadonnées, surtout quand un mauvais score est dû à un problème de moissonnage. Vu la réaction des gestionnaires de patrimoine lorsque leur jeu de données n'apparaît pas dans data.gouv avec une métadonnée qu'ils ont pourtant renseignée, ça reste une bonne précaution, et effectivement, particulièrement important pour les JDD moissonnés via `CSW-ISO-13139`

**Comment by abulte** [comment]
@nicolaskempf57 possible de mettre les `<QualityItemWarning>` derrière une prop conditionnelle (eg `showItemWarnings`) ? Sinon pas possible de répliquer le comportement actuel de data.gouv.fr en utilisant le `QualityComponent`. Merci !

**Comment by nicolaskempf57** [comment]
> @nicolaskempf57 possible de mettre les `<QualityItemWarning>` derrière une prop conditionnelle (eg `showItemWarnings`) ? Sinon pas possible de répliquer le comportement actuel de data.gouv.fr en utilisant le `QualityComponent`. Merci !

Je fais la PR pour qu'elle soit dispo dans la prochaine version.

**Comment by abulte** [comment]
@nicolaskempf57 Merci ! BTW n'hésite pas à me dire si (et où) on peut faire des PR sur `@etalab/data.gouv.fr-components`, pour ce genre de choses simples je serai ravi d'aider.
