### ISSUE TITLE
Accès unifié à la documentation

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#190]
Depuis la page d'accueil, les éléments de documentation sont accessibles depuis la section la bouquet et le bandeau d'alerte. Par ailleurs,  les recommandations ISO/DCAT ne sont pas accessibles depuis ecologie.data.gouv.fr.

Je propose d'ajouter une accès unifié vers toute la documentation disponible à ce jour.

**Comment by streino** [comment]
Pour moi le "travaux en cours" et les recommandations ISO-DCAT c'est pas le même public. J'ai peur que trop de doc tue l'info.

Je verrais bien un "travaux en cours" très synthétique qui permet à l'utilisateur (quel qu'iel soit) qui débarque sur ecologie.dgfr de comprendre ce qui se passe. Cette synthèse peut bien entendu renvoyer vers des docs spécialisées que l'utilisateur est libre de consulter selon ses centres d'intérêt.

Quand je dis "ce qui se passe", je vois un truc qui cause de :
- Pourquoi y a pas beaucoup de données
- Pourquoi les fiches qu'il y a sont pas gégé/incomplètes
- Pourquoi il y a que 2 bouquets
- Pourquoi y a plein de features que j'aimerais qui sont pas encore là
- Pourquoi c'est comme data.gouv mais c'est pas data.gouv

Chacun de ces points peut être expliqué en quelques lignes + des renvois vers des docs plus précises et/ou des documents qui trackent l'avancement, selon les besoins.

L'utilisateur lambda se fait son idée en une page, et les publics spécialisés ont loisir de creuser pour être informés sur les sujets qui les intéressent.

Par publics spécialisés j'entends par exemple :
- Producteurs
- Administrateurs de catalogues
- Utilisateurs de données
- Créateurs de bouquets
- (d'autres personna ?)

Donc plus qu'un reroot, IMO on a besoin de pondre cette synthèse pour pouvoir y raccrocher la doc existante.

Pour moi "travaux en cours" n'est pas un angle structurant pour de la doc. Pour l'instant, tout est en cours, et par la suite les sujets "en cours" vont évoluer alors qu'on aimerait que la structure de la doc reste stable.

Par contre chaque thématique (ou chaque public visé, à voir quelle structuration a le plus de sens) peut avoir une section travaux en cours vers laquelle on peut pointer depuis une page de landing qui synthétise l'ensemble des travaux en cours à l'instant t, et qu'on peut linker depuis la top-notice.

**Comment by Thesauruv** [comment]
Se pose également la question de renvoyer vers la documentation de data.gouv : https://guides.data.gouv.fr/

**Comment by ghost** [comment]
@DanFluture275 : il faudra définir le besoin de ce ticket
Actuellement, 2 éléments ont été ajoutés pour accéder à la documentation :

- Dans la homepage, dans la section "FAQ" en ouvrant une entrée : réponse "rapide" à la question + accès à la documentation pour plus de détail
- Dans le footer, ajout d'un lien "Documentation"

Faut-il ajouter un nouvel accès ? Pour répondre à quel(s) besoin(s) ?

**Comment by DanFluture275** [comment]
won't do suite aux évol de la home
