### ISSUE TITLE
Audit conformité RGAA

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#191]
Premières étapes : 
- [x] Demande d'accompagnement -> Ecedi
- [x] Financement -> commande groupée Ecolab
- [x] Entretien d'échantillonnage - 06/08/24
- [x] Restitution audit - 17/09/2024

**Comment by Thesauruv** [comment]
Lien DINUM : https://accessibilite.numerique.gouv.fr/

**Comment by Thesauruv** [comment]
Entretien prévu avec la société Ecedi le mardi 09/07.

**Comment by Thesauruv** [comment]
Entretien d'échantillonnage prévu le 27/08 à 16h.

**Comment by Thesauruv** [comment]
Entretien d'échantillonnage réalisé le 06/08, rapport d'audit attendu pour le 30/08.

**Comment by DanFluture275** [comment]
Rapport reçu et présenté par numerik-ea : 
[de__claration_accessibilite___rgaa_4.1.2.docx](https://github.com/user-attachments/files/17028985/de__claration_accessibilite___rgaa_4.1.2.docx)
[Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
[Grille de conformité RGAA 4.1.2 - ECOSPHERES.xlsx](https://github.com/user-attachments/files/17028984/Grille.de.conformite.RGAA.4.1.2.-.ECOSPHERES.xlsx)

-> Cloture du ticket et création de tickets pour les correctifs + contre-audit
