### ISSUE TITLE
Design/spec territorialisation v0

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#192]

**Comment by Thesauruv** [comment]
Discussion en hébdo Ecosphères prévue le 21/05.

**Comment by streino** [comment]
Atelier du 14/5 : https://docs.google.com/document/d/1odzu2QuaMjcTSOvo_OiacmnnIUspOMtGkV3BEHAgFO0

**Comment by streino** [comment]
Figma : https://www.figma.com/board/WnzhnsGcxfpagv8WE2Q4Ho/Territorialisation

OK en hebdo pour implémenter une v0 basée sur un [mécanisme léger de clonage](https://github.com/ecolabdata/ecospheres/issues/240).

La v1 reste à approfondir, a priori en se basant sur des ateliers design et/ou sur les retours de la v0. Le timing reste à définir. Ticket dédié v1 : https://github.com/ecolabdata/ecospheres/issues/241
