### ISSUE TITLE
Ajouter un CHANGELOG

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#196]
Idéalement généré automatiquement depuis git.

**Comment by abulte** [comment]
Deux approches :
- depuis les commits, e.g. https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli
  - nécessite un historique de commits propre
  - nécessite de suivre une convention de commits
- depuis les PR et autres objets GitHub, e.g. https://github.com/heinrichreimer/action-github-changelog-generator
  - seulement besoin de taguer les PRs

Dans tous les cas, les outils existants utilisent par défaut des tags ou la version du package npm pour créer une timeline. Dans notre cas ça va être compliqué de synchroniser des releases entre différents sites. Voir si possible de configurer ça autrement (i.e. "flat" sans version), ou se contenter d'empiler dans la version en cours. Mais dans ce cas quand génère-t-on le CHANGELOG ? Le worfklow standard est de le faire au moment de la release.

**Comment by streino** [comment]
La 2e approche semble plus gérable. Je suis un grand fan des historiques propres mais ça demande bcp de discipline...

Est-ce qu'on pourrait générer des changelogs par site en partant des [tags de MEP](https://github.com/opendatateam/udata-front-kit/pull/406#discussion_r1549344444) et en installant une github-action par site ? J'ai pas trouvé de réponse évidente pour [action-github-changelog-generator](https://github.com/heinrichreimer/action-github-changelog-generator) mais j'ai l'impression que ça serait jouable avec eg https://github.com/release-drafter/release-drafter (`tag-prefix` et éventuellement `version-template`).

**Comment by abulte** [comment]
Avec les notes de release générées par GitHub je pense qu'on a ce qu'il faut pour nos besoins https://github.com/opendatateam/udata-front-kit/releases/tag/ecospheres-prod-20240606-1
