### ISSUE TITLE
Nom du champ de recherche de donnée à l'ajout d'un jdd dans un bouquet

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#200]
Lors de l'ajout d'un jdd dans un bouquet en ajoutant une donnée via ecologie.data.gouv.fr j'ai accès à un univers plus large que juste ecologie.data.gouv.fr 
or dans le champ de recherche il est ecrit _rechercher une donnée dans ecologie.data.gouv.fr_ ce qui est faux en soit car on tape aussi sur data.gouv
je propose qu'on mette _rechercher une donnée dans data.gouv.fr_ sauf si vous avez une idée de quelque chose de plus spécifique.

<img width="1299" alt="Capture d’écran 2024-04-10 à 09 35 14" src="https://github.com/ecolabdata/ecospheres/assets/74351881/afbe8de4-58e0-44ed-bb00-5a65415e0d32">

**Comment by streino** [comment]
Le champ de search est ok, mais le radio button affiche toujours "ecologie.data.gouv.fr"

**Comment by martyKN** [comment]
dans la réalité on recherche via ecologie.data.gouv mais dans data.gouv. Du coup que le bouton radio ait ecologie.data.gouv.fr ca ne me choque pas

**Comment by streino** [comment]
C'est tout de même plus clair d'avoir "data.gouv" dans les deux, non ? Sinon ça tient à la nuance entre "via" et "dans" au niveau des labels...

**Comment by martyKN** [comment]
plus clair, quoique, ca fait pas bizarre d'etre sur ecologie.Data.gouv qui est un catalogue et on te dit que tu recherches via data.gouv ? le débat est lancé

**Comment by streino** [comment]
Ben de fait c'est le cas depuis https://github.com/ecolabdata/ecospheres/issues/177. Donc sauf à rechanger le périmètre, la recherche *est* sur data.gouv.

**Comment by martyKN** [comment]
> Ben de fait c'est le cas depuis #177. Donc sauf à rechanger le périmètre, la recherche _est_ sur data.gouv.

oulala, voir ce qui embrouille le moins l'utilisateurice

**Comment by streino** [comment]
Mon message n'est pas parti... Le voici pour archive 😓 
> Je pars pour normaliser sur "data.gouv".
> Ca n'évitera pas la question des périmètres ecologie.dgfr _vs_ dgfr mais elle si elle doit se poser, ça n'y changera pas grand chose.
> Et au moins c'est plus cohérent d'avoir la même chose dans les deux labels qui portent sur la même action.
