### ISSUE TITLE
bouquets en brouillon

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#205]
est ce normal que je ne vois plus de brouillons sur ecologie.data.gouv avec le compte team ecosphères.
or je retrouve en ayant l'url direct https://ecologie.data.gouv.fr/admin/bouquets/edit/66154c85fc560388faeeb23e

**Comment by abulte** [comment]
Oui, l'API data.gouv.fr a changé. 

C'est réglé en dev, cf https://github.com/ecolabdata/ecospheres/issues/203.

Sera réglé sur ecologie.data.gouv.fr à la prochaine mise en prod.

**Comment by streino** [comment]
@martyKN @Thesauruv a quel point est-ce problématique en prod ? SSI il faut on prévoit un deploiement.

**Comment by martyKN** [comment]
> @martyKN @Thesauruv a quel point est-ce problématique en prod ? SSI il faut on prévoit un deploiement.

C'est quand la prochaine mise en prod? On va entamer des porteureuses de cas d'usages semaine pro (lundi 29 14h45) donc ca serait pas mal que ce soit en place

**Comment by streino** [comment]
On avait parlé d'une MEP "bugfixes" vers fin avril/début mai, donc on peut essayer de caler ça pour le 29.
