### ISSUE TITLE
Impossible de sélectionner plusieurs fois un même jeu de données dans un bouquet

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#206]
Bug apparu lors de la création du bouquet [Production d'énergie renouvelable](https://ecologie.data.gouv.fr/bouquets/production-denergie-renouvelable).

**Reproduction**
Dans l'étape 3 de du parcours de création de bouquet, j'ajoute l'indicateur suivant : 
- libellé : Puissance installée pour l'éolien et le photovoltaïque
- raison d'utilisation : Puissance en MW
- sélection du [jeu de données](https://ecologie.data.gouv.fr/datasets/5bfcc5a006e3e744e304ccf0) depuis ecologie.data.gouv.

Ajout d'un nouvel indicateur fléchant vers le même jeu de donnée : 
- libellé : Production d'électricité pour les filières éoliennes et solaires
- raison d'utilisation : Puissance exprimée en GWh/an.
- il m'est alors alors impossible de sélectionner [le même jeu de donnée](https://ecologie.data.gouv.fr/datasets/5bfcc5a006e3e744e304ccf0) renseigné plus tôt et disponible depuis ecologie.data.gouv.

**Comment by abulte** [comment]
C'est une feature :-) Un jeu de données déjà sélectionné ne peut pas être re-sélectionné. C'est assez pratique je trouve parce que ça évite de réselectionner un jeu de données au titre similaire (ex : chercher SIRENE).

On peut changer le comportement bien sûr si besoin.

**Comment by Thesauruv** [comment]
Ok, merci pour le retour ! Je m'étais dit que c'était potentiellement intentionnel. Sur le projet indicateurs territoriaux, ils font leur description par indicateur, plusieurs indicateurs pouvant être lus à partir d'un même dataset, je suis d'avis de changer le comportement.

**Comment by streino** [comment]
Pas super chaud pour ce changement, du moins à ce stade. Pour un bouquet qui a besoin de ça on va compliquer la vie de pas mal d'autres qui ne vont pas comprendre pourquoi on leur re-suggère le même jeu de données des recherches suivantes, ou pourquoi la fonction "ajouter à un bouquet" n'est pas désactivée pour le bouquet alors que le JDD y a déjà été ajouté. On s'éloigne aussi de la notion de topic, avec une complexité qui ne sera pas forcément simple à faire adopter upstream par data.gouv.

Si vraiment c'est bloquant pour les indicateurs et qu'on décide de l'implémenter, je mettrais bien ça derrière un switch à activer explicitement.

**Comment by abulte** [comment]
> On s'éloigne aussi de la notion de topic, avec une complexité qui ne sera pas forcément simple à faire adopter upstream par data.gouv.

Exact, ce n'est pas vraiment compatible avec la notion de liste de jeux de données dans un Topic. Par définition le jeu de données n'apparait qu'une fois dans la liste.

**Comment by streino** [comment]
@Thesauruv peut-on avoir une description du cas d'usage "indicateurs" plus précise, pour voir ce qu'on peut faire ?
Ils font un unique bouquet pour tous les indicateurs, ou un bouquet par indicateur ? Dans l'idéal, à quoi voudraient-ils que le(s) bouquet(s) ressemble(nt) au final ?

**Comment by Thesauruv** [comment]
@streino @abulte Le projet indicateurs territoriaux liste dans [ce référentiel](https://docs.google.com/spreadsheets/d/16MZwxQcpqofshSg0qwpr5e9TrNYuYQGVkShWLqnu224/edit#gid=1089879935) 117 indicateurs cibles dont 35% proviennent d'un même jeu de donnée produit par le SDES. Le problème avec ce type de source est que les indicateurs qui y sont rassemblés ne sont pas d'une qualité homogène : différences dans les millésimes, les fréquences de production, la fiabilité des sources dont ils sont eux-mêmes issues (question de généalogie), etc. Ce sont ces différences de qualité entre les indicateurs qui expliquent notamment le besoin d'une documentation par indicateur, approche que l'on voit se répéter : projet pilote de la DITP, travail sur les CRTE porté par la Direction au Développement Durable, etc.

Documenter par indicateur est par ailleurs similaire à l'approche de la Métropole de Lyon d'une documentation par "facteur" (voir calque de plantabilité ou l'itinéraire de fraîcheur).

**Comment by Thesauruv** [comment]
Même blocage soulevé par les créateurs du bouquet Bat Adapt : https://ecologie.data.gouv.fr/bouquets/bat-adapt-1
