### ISSUE TITLE
Matrice politiques publiques/bouquets

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#208]
Cette matrice des cas d'usage doit permettre de documenter spectre du déploiement des bouquets, les avancées du déploiement (contacts par politique publique, création de bouquets) et renseigner des éléments de priorisation pour la stratégie de déploiement.
 
Enjeux externes à l'équipe projet : 
- Montrer que nous travaillons à l'articulation entre objectifs nationaux et initiatives locales (lien fort avec la territorialisation de la planification écologique),
- Question récurrente sur le déploiement : comment priorisez-vous les cas d'usage ?

**Comment by martyKN** [comment]
Itération 1 https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/jngELBW4hurTl6kYRbLo/~/changes/2/

**Comment by Thesauruv** [comment]
Reformulation du besoin : 
- structurer le déploiement avec un outil/approche de type CRM
- notion de PPG : trop généraliste
- définir des critères de priorisation des cas d'usage en lien avec le déploiement indépendamment d'une matrice sur les politiques et leurs objectifs
- pour des initiatives locales en lien avec l'adaptation au changement climatique (végétalisation), pas systématiquement de politique nationale avec des objectifs nationaux

**Comment by streino** [comment]
CRM en place, pas d'autre actions prévues de notre côté.
