### ISSUE TITLE
Documentation du moissonnage à destination des gestionnaires de catalogues

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#209]
Présenter le mécanisme de moissonnage. 
Faire le lien avec les préconisations (cf https://github.com/ecolabdata/ecospheres/issues/124).
Documenter le processus de création des points de moissonnage pour le déploiement.

**Comment by Thesauruv** [comment]
Recoupage avec https://github.com/ecolabdata/ecospheres/issues/198

**Comment by streino** [comment]
Je dirais même plus que recoupage ;)
Je merge le contenu de ce ticket dans #198.
