### ISSUE TITLE
Cadrage de la prestation d'Alkante sur Prodige

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#210]
Synthèse des points à aborder : 

**Prodige4 (GN3)**

1. Tester les options identifiées.
- Option "fieldSpecificAnalyzer". Cf mail d'analyse, repris dans https://github.com/ecolabdata/ecospheres/issues/184#issuecomment-2059132619.
- Option "GN standard", si première option KO. Cf [doc Géonetwork](https://docs.geonetwork-opensource.org/3.12/customizing-application/configuring-search-fields/). Consiste à modifier xslt + conf.
Pour chaque option : 
- Acceptable d'un point de vue opérations et mise en prod (compte tenu de la disponibilité des environnements prodige en cette période de montée de version) ?
- Tester l'option sur un prodige avec de vraies données.

2. Anticiper la montée de version vers Prodige5.
- Passer par des Portails plutôt que des endpoints CSW virtuels dès la version 4 ?
- Besoin d'ajuster le filtre sur l'orga ?
- Autres points à anticiper/tester ?

3. Déployer sur la plateforme Prodige de DatARA (ou un autre candidat si impossible sur DatARA).
- Si on a une solution et si Julien la valide bien entendu !

4. Définir la procédure de MEP + évaluer le délai.
- Applicable à toute les plateformes prodige ou cas particuliers (par ex selon dispo environnements) ?

5. Documenter :
- La procédure de création d'un portail ou csw virtuel selon l'approche retenue.
- Les modifs éventuelles pour migrer la fonctionnalité en Prodige5.

**Prodige5 (GN4)**

1. Erreur "Invalid XPath expression: "/csw:Record//"" sur [https://catalogue-test.prodige-ecolab.fr/geonetwork/DREAL_ARA/fre/csw](https://catalogue-test.prodige-ecolab.fr/geonetwork/DREAL_ARA/fre/csw?SERVICE=CSW&REQUEST=GetCapabilities). Update : l'erreur ne se produit que lorsqu'on query avec elementSetName=full. Ca fonctionne avec elementSetName=brief et elementSetName=summary.
Julien dit l'avoir sur GetCapabilities. Je ne reproduis pas mais j'ai le problème sur GetRecords.
2. Autres points éventuels à définir une fois qu'on pourra tester sur [https://catalogue-test.prodige-ecolab.fr/geonetwork/DREAL_ARA/fre/csw](https://catalogue-test.prodige-ecolab.fr/geonetwork/DREAL_ARA/fre/csw?SERVICE=CSW&REQUEST=GetCapabilities)
3. Documenter la procédure de création d'un portail.
- Si différent du point 4 Prodige4 et/ou pas suffisament documenté côté Géonetwork.

Les points suivants sont pressants pour valider l'approche "endpoint par orga" : Prodige4 points 1-3 + Prodige5 points 1-2. Sinon il faudra envisager un plan B (technique ou planning), et le plus tôt sera le mieux.

**Comment by streino** [comment]
CR du point avec Benoist d'Alkante :
1. Benoist se penche dès maintenant sur les tests endpoint/portail csw. Dès qu'il a qqch en place il nous communique l'url pour tester un moissonnage sur [demo.dgfr](http://demo.et/) et contactera aussi Julien pour valider que le patch fonctionne et n'a pas d'effets de bord sur DatARA.
2. Démarrage du reste de la presta possible fin mai. Premier focus sur la "migration du patrimoine" pour appliquer les préconisations les plus critiques aux catalogues Prodige.
   - Ils ont déjà fait ce genre de manips en allant directement modifier les XML Géonetwork en base à coup de requête SQL + scripts. L'idéal serait de pouvoir utiliser les mêmes scripts de transfo pour Prodige et les autres plateformes. L'avantage de cette approche est que Prodige l'emploie déjà, donc ça sera plus facile à vendre aux admins.
   - La plupart des admins catalogue ont accès à leur base, donc on pourrait aussi envisager un outil plus générique permettant aux admins d'appliquer eux-mêmes les transformations.
3. Ils ont un pipeline automatisé de déploiement, donc possible d'appliquer les modifs des points 1 et 2 sur une liste de catalogues Prodige en batch.
4. Tenir compte des versions Prodige déployées dans notre plan de déploiement. Par exemple, plus simple de tester les modifs sur les catalogues qui n'ont pas encore migré leur env de test à Prodige 5. J'ai demandé s'il pouvait nous transmettre la liste catalogues et leurs versions.
5. Prévoir de communiquer lors d'un jeudi Prodige ou pendant leurs Journées en juin (Benoist va en parler à Clément).
6. Prochain point avec Benoist le 16/5 14h pour cadrer plus globalement la presta. D'ici là il faut qu'on priorise et spécifie un peu plus nos besoins.

**Comment by streino** [comment]
Vu en réunion et hebdo : 
- UOs "application des préconisations" (section 1 du devis) : Favoriser les devs génériques Geonetwork plutôt que spécifiques Prodige.
- UOs "métadonnées de contacts" (section 2 du devis) : RAS. Spécifique Prodige.
- UO "automatisation création endpoints virtuels" : Probablement pas nécessaire (quels catalogues Prodige auront beaucoup d'endpoints à créer ?). Retarder la décision sur ce point, avec possibilité de réaffecter les jours sur les autres UOs.
