### ISSUE TITLE
Tester un moissonnage à partir d'une plateforme GéoOrchestra

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#211]

**Comment by streino** [comment]
Voir avec le Craig ou GeoBretagne

**Comment by streino** [comment]
Posté sur Slack : 
> Au sujet du moissonnage GéOrchestra, j'avais oubliqué qu'ils travaillaient déjà sur le moissonnage DCAT par data.gouv : https://github.com/georchestra/georchestra/issues/4182. C'est donc une autre option pour atteindre une qualité de moissonnage acceptable.
> Dans tous les cas ça passe pas du CSW, donc la question des endpoints virtuels reste posée.
[craig.fr](http://craig.fr/) étant en Géonetwork 4, c'est plutôt une bonne nouvelle.
> Et si jamais, GéOrchestra maintient son fork de Géonetwork (pourquoi ? [je ne sais pas...](https://github.com/georchestra/geonetwork/issues/96)), donc on au besoin on devrait pouvoir pousser nos modifs direct chez eux.

**Comment by streino** [comment]
GéoBretagne a déjà fait des tests avec data.gouv.
Moissonneur csw-iso-19139 avec filtre sur orga : https://demo.data.gouv.fr/fr/admin/harvester/660f9a38c7ed4fe5025a3670

Donc on est bon pour GéOrchestra sur la partie moissonnage de base :) Reste l'éventuel besoin d'appliquer les précos, mais on va suivre https://github.com/georchestra/georchestra/issues/4182 et on fera un ticket dédié pour la prise en charge si ni 4182 ni la moulinette prévue ne répondent aux problèmes remontés.
