### ISSUE TITLE
Communication auprès des services déconcentrés sur le moissonnage

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#212]
Communiquer à l'ensemble des services déconcentrés sur notre démarche.

Recommandations de J. Lardemer : 
- Communiquer auprès des chefs de pôles SIG, + chefs de services connaissances en copie (voir avec MiCo, a priori pas de liste de diffusion existante),
- Mettre en copie : labo.add.dreal@developpement-durable.gouv.fr et  labo.add.ddt@developpement-durable.gouv.fr (mails à vérifier);
- Rappeler que nous avions déjà présenté notre démarche lors de wébinaires/séminaires.

Dépendances avec : 
https://github.com/ecolabdata/ecospheres/issues/209
https://github.com/ecolabdata/ecospheres/issues/210
https://github.com/ecolabdata/ecospheres/issues/124

**Comment by streino** [comment]
Préparer slides pour expliquer ce qui bloque la MEP moissonnages : 
- Changement Géocat à moissonnage direct
- Métadonnées critiques

**Comment by Thesauruv** [comment]
Vu avec Marina de la Mission Connaissance : une communication sur ce sujet est prévue lors de la rencontre des chefs du réseau connaissance (en plus du mail) prévue le 12 juin après-midi.

**Comment by streino** [comment]
Présentation lors de la journée Prodige le 3 juin. ~30 personnes.

**Comment by streino** [comment]
Présentation au webinaire moissonnage le 9/9. 60+ personnes.

**Comment by streino** [comment]
@Thesauruv D'autres plans ou on ferme ce ticket ?

**Comment by Thesauruv** [comment]
@streino @DanFluture275 Je propose de fermer ce ticket et de se concentrer sur une actualisation de https://github.com/ecolabdata/ecospheres/issues/314 avec @benoitdavidfr.
