### ISSUE TITLE
Gérer l'impact d'une suppression de jeu de données sur data.gouv.fr

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#221]
Quand un jeu de données est supprimé sur data.gouv.fr et référencé dans un bouquet (ex [toilettes publiques](https://www.data.gouv.fr/api/2/datasets/6116220b56def3618341d231/) dans [Itinéraire fraicheur](https://ecologie.data.gouv.fr/bouquets/itineraires-fraicheur), une erreur 404 s'affiche.

![Image](https://github.com/ecolabdata/ecospheres/assets/119625/210b51a6-99ce-473a-a54d-8f04a642c270)

Quel devrait être le comportement dans ce cas ?

Quelques solutions :
1. ignorer silencieusement 😬 
2. afficher l'erreur au niveau du jeu de données afin d'inciter le producteur à modifier son bouquet 👍 
3. script de purge des jeux de données supprimés des bouquets (notification possible du producteur sur un script backend mais moyen à déterminer : discussion, email (lequel ?)...) 🍧 

Related https://github.com/datagouv/data.gouv.fr/issues/1359 #217, pour gérer proprement l'erreur quand on est connecté.

**Comment by streino** [comment]
Une solution de plus : 
4. Switcher le JDD concerné en affichage "catalogue externe" (simple lien URL).

Je penche vers 2 + 4. Avec une précaution à prendre sur l'erreur affichée car l'absence d'un JDD peut être temporaire (dgfr down pile quand on fait la requête) ou plus permanente (grand lyon qui bork sa màj).

On aura sans doute besoin de 3 à un moment ou un autre, mais ça deviendra utile lorsqu'on aura bcp de bouquets et donc besoin de traiter en batch.

**Comment by abulte** [comment]
Normalement si on déclenche sur 404 on n'aura pas de faux positif (plutôt 5xx).

Pour 4, je suis un peu réticent à basculer automagiquement une valeur du schéma lorsqu'un usager visite la page.

**Comment by streino** [comment]
Je pensais pas basculer la valeur dans le schéma, juste varier l'affichage. Mais si on restreint aux 404 le lien utile n'a pas de valeur, donc pas besoin.
