### ISSUE TITLE
Expand incorrect après avoir réorganisé les jdd dans un bouquet

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#226]
**Pour reproduire**

- Dans un bouquet contenant plusieurs jdd (dans l'ordre : A, B, ...)
- S'assurer que tous les jdd sont repliés
- Déplier l'item B (position 2)
- Déplacer l'item B de la position 2 à la position 1

**Attendu**

Les items se sont déplacé en conservant leur statut déplié/replié :
> B (déplié), A (replié), ...

**Observé**

Les items se sont déplacé sans leur statut => inversion déplié/replié entre A et B :
> B (replié), A (déplié), ...

Observable avant et après PR #434

**Comment by abulte** [comment]
Nice one 🙃 

J'ai hésité à désactiver l'accordéon quand on trie, ça serait peut-être pas plus mal et ça évitera ce genre de bugs.

**Comment by streino** [comment]
Ça serait le plus simple mais ça veut dire qu'un utilisateur qui a déplié tout un tas d'items va se retrouver avec tout replié après une réorganisation. Alors qu'on conserve les états sur un ajout/modification de jdd (tiens, ça bug aussi sur un delete).
