### ISSUE TITLE
Passer d'une liste de jeux de données à une liste de facteurs

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#228]
La question de basculer d'une liste de jeux de données à une liste de facteurs/indicateurs a été soulevée dans plusieurs contextes : 
- https://github.com/ecolabdata/ecospheres/issues/206 
- https://github.com/ecolabdata/ecospheres/issues/192

Liste non-exhaustive de points à couvrir : 
1. Quelle complexité ça ajoute pour l'utilisateur ? 
1. Quel nom utiliser pour le concept de "facteur" ?
1. Relation entre "facteur" et jdd ? Viser directement N:N ou limiter à N:1 dans un premier temps ?
1. Articulation avec l'objet "topic" de data.gouv ?

**Comment by streino** [comment]
Approche par "facteurs" du calque de plantabilité : https://erasme.notion.site/Kit-de-d-couverte-du-calque-de-plantabilit-4a4ce2b615874903afe204ddbd5b94cd

**Comment by DanFluture275** [comment]
Won't do
