### ISSUE TITLE
Mieux structurer la section "Jeu de données" de la modale d'ajout de JDD

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#230]
<img src="https://github.com/ecolabdata/ecospheres/assets/30210525/43daf168-d83c-457c-8b28-ed50bc55b12f" width=400/>

"Vous ne trouvez pas ..." devrait être au même niveau de visibilité que "Rechercher un jeu de données dans data.gouv.fr", le tout à l'intérieur de la section "Jeu de données".

Ça me semble difficile de réduire "Vous ne trouvez pas ...", donc faudrait-il agrandir "Jeu de données", et pas conséquent "Libellé" et "Raison d'utilisation" ? Agrandir ou bold ou ... ?

_Originally posted by @streino in https://github.com/opendatateam/udata-front-kit/pull/434#discussion_r1601850160_

**Comment by abulte** [comment]
Après test, supprimer le label et garder seulement le placeholder fait un peu vide. Peut-être mettre seulement "Rechercher" dans le placeholder pour éviter trop de répétition et amener cohérence avec couverture territoriale sur la page de liste de bouquets. Le cas échéant, harmoniser aussi couverture territoriale dans BouquetEditForm. TLDR: rechercher partout en placeholder dans les MultiSelect et hint-text détaillé partout.

**Comment by streino** [comment]
Sounds good to me (SGTM?)

**Comment by abulte** [comment]
Oups wrong issue, je déplace dans #231

**Comment by DanFluture275** [comment]
A considérer dans les tests utilisateurs
