### ISSUE TITLE
Doublon texte dans la modale ajout de JDD

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#231]
<img src="https://github.com/ecolabdata/ecospheres/assets/30210525/f2b08600-c721-4163-aa0d-65e54edd09f8" width="500"/>

Deux fois la phrase "Rechercher une donnée dans data.gouv.fr" au dessus et dans le select.

À articuler avec https://github.com/ecolabdata/ecospheres/issues/230.

**Comment by abulte** [comment]
Après test, supprimer le label et garder seulement le placeholder fait un peu vide. Peut-être mettre seulement "Rechercher" dans le placeholder pour éviter trop de répétition et amener cohérence avec couverture territoriale sur la page de liste de bouquets. Le cas échéant, harmoniser aussi couverture territoriale dans BouquetEditForm. TLDR: rechercher partout en placeholder dans les MultiSelect et hint-text détaillé partout.

**Comment by streino** [comment]
Sounds good to me (SGTM?)

**Comment by narduin** [comment]
D'un point de vue accessibilité, il faut à tout prix [éviter d'utiliser le placeholder comme un label.](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/placeholder#accessibility_concerns)
Le placeholder doit servir d'exemple de saisie attendue voire ne pas être utilisé du tout 😄 
Par exemple ici le label pourrait être: "ex: Plan cadastral Poitiers"

**Comment by DanFluture275** [comment]
Traité dans le cadre du sujet RGAA
