### ISSUE TITLE
La liste de suggestion de jdd peut déborder

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#233]
Exemples plus ou moins gênants :

Ecrase le titre
<img width="500" src="https://github.com/opendatateam/udata-front-kit/assets/119625/ce20fc48-bc4f-419f-9f29-55e580867d2f">

Dépasse de la modale
<img width="500" src="https://github.com/opendatateam/udata-front-kit/assets/30210525/2e5051d5-cf99-4bcc-b3fa-491a103c1790">

**Comment by streino** [comment]
Est-ce qu'on s'en sortirait mieux en utilisant une page plutôt qu'une modale ?

**Comment by martyKN** [comment]
est ce que quand ca dépasse la modale, tu peux scroller ? 
petite video de mon issue


https://github.com/ecolabdata/ecospheres/assets/74351881/9660621f-63a3-424e-8e98-b17c8e8b8423

**Comment by abulte** [comment]
Yes

https://github.com/ecolabdata/ecospheres/assets/119625/74ef3996-f050-4c44-a2e3-52401088c394

**Comment by martyKN** [comment]
bizarre alors, j'arrive a reproduire la bug, mais ce n'est pas à tous les coups

https://github.com/ecolabdata/ecospheres/assets/74351881/85295a57-590e-4498-99a0-083a0dff3891
