### ISSUE TITLE
Taille des cartes du select dataset

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#236]
Quand j'ajoute une donnée dans un bouquet, je suis alors dans la fenetre pop-up et j'utilise le search
-> Est ce que le dsfr offre une version plus petite de la liste déroulante. 
Je sais pas si c'est moi qui ai une super vue ou si les jdd présentés sont vraiment gros mais je trouve que ca prend enormement de place sur mon ptit ecran
<img width="794" alt="Capture d’écran 2024-05-22 à 10 00 14" src="https://github.com/ecolabdata/ecospheres/assets/74351881/50b0cc30-93e9-4bc9-9c18-e309a6537622">

**Comment by abulte** [comment]
C'est les cartes qui sont trop grosses ?

Rien à voir avec le DSFR, ce sont des cartes data.gouv.fr. On peut jouer sur leur style dans le select, mais il me faudrait une maquette ou autre pour voir ce que tu as en tête.

**Comment by martyKN** [comment]
<img width="471" alt="Capture d’écran 2024-05-22 à 10 21 24" src="https://github.com/ecolabdata/ecospheres/assets/74351881/60892bd4-14c2-4874-947b-46642d9e6a7e">

j'ai réduit de 2 points chaque typo

je t'ai tag sur le figma
