### ISSUE TITLE
Transférer les documents Ecosphères à partager dans le dossier K:\SRI/03 ECOLAB

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#24]
Transférer les documents Ecosphères à partager dans le dossier K:\SRI/03 ECOLAB
- [x] Délégation de gestion DINUM

Prestations (consultation, proposition commerciale, demande d'achats, bon de commande, devis, CSF(s))
- [x] Enquête Valentin Labit
- [ ] Marché Innovant Alexandre Bulté
- [x] Prestation Design Alexandra Douine : manque le bon de commande
- [x] Prestation Frontend multi
- [x] Prestation Qualité de la Donnée Datactivist
- [x] Expressions des besoins et bons de commande dans le cadre de la délégation de budget
- [x] Alkante

**Comment by Thesauruv** [comment]
@martyKN Pourrais-tu m'envoyer les bons de commandes pour les prestations de Valentin et d'Alexandra ?
@streino Je t'envoie une invitation pour faire un point sur la doc du marché innovant passé avec Alexandre.

**Comment by martyKN** [comment]
normalement j'ai tout rangé dans un dossier sous K...peut etre pas au bon endroit du coup. je te transfère tout par mail
