### ISSUE TITLE
Retours à la ligne markdown

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#244]
Quand je suis sur le champ description dans l'ajout d'un bouquet
j'ecris mon texte - je fais 'entrée' pour aller à la ligne
je valide l'edition 
le texte n'est pas à la ligne, il reste sur la meme ligne (cf screen)
<img width="799" alt="Capture d’écran 2024-05-29 à 10 30 30" src="https://github.com/ecolabdata/ecospheres/assets/74351881/09e7c2e4-7250-479d-99aa-19e25058f934">
<img width="583" alt="Capture d’écran 2024-05-29 à 10 30 36" src="https://github.com/ecolabdata/ecospheres/assets/74351881/450a4974-e423-4446-b3b8-d074c0a9cf3f">
et quand je fais entrée 2 fois le texte fait bien un saut de ligne
<img width="697" alt="Capture d’écran 2024-05-29 à 10 30 44" src="https://github.com/ecolabdata/ecospheres/assets/74351881/f2d7e3f7-6dc5-4ff7-ba70-b5463cd94947">
<img width="835" alt="Capture d’écran 2024-05-29 à 10 30 51" src="https://github.com/ecolabdata/ecospheres/assets/74351881/cc3f1de0-2e1d-49f2-a270-2e03115052ca">

**Comment by streino** [comment]
C'est le comportement normal de markdown, cf https://fr.wikipedia.org/wiki/Markdown :

```
Les paragraphes sont séparés
par une ligne laissée vide.

Deux espaces à la fin d'une ligne  
produisent un saut de ligne.
```

**Comment by abulte** [comment]
Ca dépend des différentes specs je crois. Genre GFM (ici):
cette ligne est à la ligne.

**Comment by abulte** [comment]
Et sur data.gouv.fr c'est OK donc je dirais bien bug

https://demo.data.gouv.fr/fr/datasets/jdd-ecospheres/

<img width="311" alt="Capture d’écran 2024-05-29 à 10 56 20" src="https://github.com/ecolabdata/ecospheres/assets/119625/1dac7eed-403e-4d36-9164-eea71c2ccae5">

**Comment by abulte** [comment]
(Il me semble avoir déjà traité ça quelque part et c'est une tannée avec un textarea standard de mémoire)

**Comment by martyKN** [comment]
mais j'ai l'impression que ca marchait dans le passé. En tout cas j'ai pas de souvenir d'avoir galéré avec les retours à la ligne sur ecologie.Data.gouv

**Comment by abulte** [comment]
A moins que quelque chose ait changé côté data.gouv.fr (je ne crois pas), ça ne marchait pas en janvier https://deploy-preview-311--ecospheres.netlify.app/bouquets/bouquet-deploy-preview-311.

**Comment by martyKN** [comment]
ca marchait en avril sur la prod 
https://ecologie.data.gouv.fr/bouquets/itineraires-fraicheur

**Comment by streino** [comment]
Ah les joies des standards pas vraiment standard... Désolé pour la clôture trop rapide :pray:

**Comment by abulte** [comment]
Fun fact: https://ecologie.data.gouv.fr/bouquets/itineraires-fraicheur utile le [trick "double espace"](https://www.markdownguide.org/basic-syntax/#line-breaks) pour créer une nouvelle ligne.

> You can use two or more spaces (commonly referred to as “trailing whitespace”) for line breaks in nearly every Markdown application, but it’s controversial.

Donc ça marche toujours chez nous et notre parser Markdown semble être spec-compatible.

Reste à voir pourquoi ça marche sans double espace côté data.gouv.fr et si on peut/veut faire la même chose. A noter que côté data.gouv.fr on est dans un éditeur HTML, qui peut ajouter des `<br>` à volonté.

**Comment by abulte** [comment]
Les option `breaks` + `gfm` devraient faire ce qu'on veut au parsing : https://marked.js.org/using_advanced#options. Et on retombe sur nos pieds : ça marche ici (dans GitHub).
