### ISSUE TITLE
Bouquet "élaboration d'un document d'urbanisme"

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#246]
Bouquet co-construit avec l'équipe DocUrba et disponible à partir de [ce lien](https://ecologie.data.gouv.fr/bouquets/elaboration-ou-evolution-dun-document-durbanisme). Pour DocUrba, fort enjeu de réplicabilité. Ci-dessous, éléments de documentation du PAC Inno.

[Reponses_questionnaire_DDT_AC_10_2020-3.ods](https://github.com/ecolabdata/ecospheres/files/15499011/Reponses_questionnaire_DDT_AC_10_2020-3.ods)
[20210406_etat_lots_de_donnees-3.ods](https://github.com/ecolabdata/ecospheres/files/15499012/20210406_etat_lots_de_donnees-3.ods)

**Comment by martyKN** [comment]
la dernière version du bouquet est sur demo, cela permet d'avoir accès aux données ddt 74 + dreal ARA https://demo.ecologie.data.gouv.fr/bouquets/elaboration-ou-evolution-dun-document-durbanisme-clone-haute-savoie-test-geoide
@Thesauruv

**Comment by DanFluture275** [comment]
En attente des retours des bureaux d'études.
Voir les éventuels retours à traiter, puis déploiement en prod. Attention à s'assurer de la présence des données DREAL ARA sur la prod au préalable si possible.
