### ISSUE TITLE
Modale ajout de donnée dans un bouquet via un url

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#248]
Quand j'ajoute un jdd dans un bouquet en cliquant sur le bouton radio via url alors je vois ca 
<img width="792" alt="Capture d’écran 2024-06-04 à 09 59 58" src="https://github.com/ecolabdata/ecospheres/assets/74351881/722b7873-a1fd-4bf3-891a-1b815fc74444">
est ce que c'est possible de faire un drop down pour voir que le champ url s'est ajouté?

_PS : Il me semble qu'on en avait parlé dans un autre ticket mais je retrouve plus_

**Comment by abulte** [comment]
#242 :-)

**Comment by martyKN** [comment]
ah oui c'etait pas loin et pas vieux ;)

**Comment by abulte** [comment]
Je rouvre parce qu'il y a plus de choses dans #242 et j'ai un fix potentiel pour cette partie.
