### ISSUE TITLE
Clonage bouquet : pb sur la recuperation d'informations

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#253]
Je viens de cloner le bouquet sur l'elaboration d'un document d'urbanisme
le bouquet parent est celui la 
https://ecologie.data.gouv.fr/bouquets/elaboration-ou-evolution-dun-document-durbanisme
le bouquet enfant est celui la 
https://ecologie.data.gouv.fr/bouquets/elaboration-ou-evolution-dun-document-durbanisme-1

Le clonage n'a pas récupéré les modifications faites dans un second temps par Hermance : description des données ligne 1 et 2

**Comment by abulte** [comment]
Ca marche pour moi https://ecologie.data.gouv.fr/bouquets/clone-alb-tmp.

Je pense que tu as cloné le bouquet en ayant en local (dans ton navigateur) une version un peu obsolète (qui datait du dernier chargement du bouquet d'Hermance dans ton navigateur).

On peut éventuellement se protéger contre ça en forçant la récupération de la dernière version au moment du clone. Mais : est-ce que ça vaut le coup ? Est-ce qu'on ne veut pas au contraire cloner exactement ce qu'on affiche au clic sur "Cloner" ?

**Comment by martyKN** [comment]
en effet ca marche après avoir fermé mon navigateur et ré-ouvert (sans supprimer cache et cookies)

**Comment by martyKN** [comment]
`est-ce que ça vaut le coup ? Est-ce qu'on ne veut pas au contraire cloner exactement ce qu'on affiche au clic sur "Cloner" ?`

je pense que ca vaut pas le coup :)
