### ISSUE TITLE
Affichage d'une recherche dans la modale

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#255]
à l'ajout d'un jdd, la modale s'ouvre
je recherche dans la barre de recherche et j'ai la liste des resultats qui s'affiche au dessus
je ne peux pas scroller pour voir le 1er resultat
![Capture d’écran 2024-06-19 à 09 38 03](https://github.com/ecolabdata/ecospheres/assets/74351881/6ea4c793-2f04-4980-8a83-1a7770c6ff21)
Dans le screenshot je ne peux pas voir le titre de la 1ere donnée et je ne peux pas savoir si il y en a d'autres au dessus.
Je suis sur un ecran 20 ou 22 pouces

**Comment by abulte** [comment]
Voir https://github.com/ecolabdata/ecospheres/issues/233

En revanche bizarre que tu n'arrives pas à scroller, normalement c'est faisable.

**Comment by martyKN** [comment]
je peux pas scroller vers le haut => je suis bloqué en haut, mais je peux descendre. et la bizarre ca a pas reproduit ...

**Comment by abulte** [comment]
Je pense qu'on peut continuer sur #233 si besoin, je ferme ici.
