### ISSUE TITLE
Évaluation moissonnage DDT95

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#261]

**Comment by Thesauruv** [comment]
Intégration d'une v0 du gestionnaire de patrimoine prévue avant les tests.

**Comment by streino** [comment]
CR session de review avec la DDT 95 : 
- Globalement satisfaits de améliorations.
- Incompréhension sur la date de "Dernière mise à jour" mise en valeur par data.gouv, qui n'a pas de sens pour les moissonnages -> https://github.com/ecolabdata/ecospheres/issues/422.
- Explication des pbs de "lien vers la source". Complexité difficile à expliquer, mais le sujet va disparaitre grâce à https://github.com/ecolabdata/ecospheres/issues/347.
- Licence ouverte 1.0 non détectée -> ajout manuel du label GeoIDE correspondant sur demo + prévoir amélioration du "guesser" (cf [mattermost](https://mattermost.incubateur.net/betagouv/pl/1qhopszbejgsb81oduoa63xo4a)) ?
- Présentation du dashboard. Intérêt de l'utiliser pour "nettoyer" leur catalogue avant la MEP.
- Prévoir reprise contact pour accompagnement MEP avant mi-novembre. Ils me recontacteront d'ici là s'ils sont prêts avant.
