### ISSUE TITLE
Tests "moulinette XSLT" DatARA

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#262]
Tester la moulinette XSLT sur les données DatARA.

**Comment by streino** [comment]
Moulinette livrée par Alkante : https://github.com/ecolabdata/ecospheres-transformer

**Comment by streino** [comment]
Tests basiques concluants. 1 bug remonté à Alkante.

Par contre, les modifications de templates ne sont pas forcément bien gérées par les vues (simplifiée, complète) de l'interface Geonetwork. Il va falloir creuser ce point.

**Comment by streino** [comment]
En attente correctifs et déploiement par Alkante sur DatARA preprod.

**Comment by DanFluture275** [comment]
related #264

**Comment by streino** [comment]
Abandon d'ecospheres-transformer pour ISOmorphe.

Tests ISOmorphe concluants sur les données DatARA.

On peut fermer ce ticket, on traitera les éventuels retours des tests Alkante par de nouveaux tickets plus spécifiques.
