### ISSUE TITLE
Données HVD dans ecologie.data.gouv

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#271]
Les organisations de catalogues thématiques du pôle ministériel dont les données ont été moissonnées par data.gouv dans le cadre de HVD (High Value Datasets) n'ont pas encore été référencées dans ecologie.data.gouv. Par exemple : 
- les données sur l'eau : https://www.data.gouv.fr/fr/organizations/systeme-d-information-sur-l-eau/
- les données sur la biodiversité : https://www.data.gouv.fr/fr/organizations/systeme-dinformation-sur-la-biodiversite/

Actions : 
- Vérifier avec data.gouv la liste des organisations du pôle ministériel dont les données ont été remontées dans le cadre d'HVD.
- Compléter la configuration correspondante pour ecologie.data.gouv

**Comment by Thesauruv** [comment]
Dans la [table plateformes du Grist](https://grist.incubateur.net/o/ecospheres/k3YQHL3Bmrhm/Moissonnages/p/4), voir celles traitées par data.gouv. Ces informations ont notamment été revues par Clarisse qui a également fait le lien vers le fichier export-harvest de data.gouv, contenant l'information sur les organisations associées.

**Comment by streino** [comment]
D'après le grist, les moissonneurs déjà en place côté data.gouv sont : 
```
organization                                                        organization_id           backend   created_at
Agence Régionale du Numérique et de l’intelligence artificielle     5b4f5364c751df0bb1c28756  ckan      2023-05-10T09:46:18.111000
Amiens Métropole - Communauté d'Agglomération                       62ac72051170a1fcc75a9a35  csw-dcat  2024-06-18T07:46:18.730000
Atmo Bourgogne-Franche-Comté                                        5ddbf5ff6f444103e11e9d3d  ckan      2020-10-26T13:54:30.314000
Cerema                                                              5c812a16634f416583ed1876  csw-dcat  2024-03-29T12:47:35.538000
Communauté d’Agglomération du Centre Littoral de Guyane             60180bd0925674d91a968a1b  dcat      2021-06-09T18:42:06.887000
Conseil départemental du Finistère                                  5a86b30588ee38553adbaa6e  csw-dcat  2024-03-01T08:57:19.045000
DREAL Bourgogne-Franche-Comté                                       5835d0a088ee3842afc65bb3  ckan      2020-04-15T09:21:35.638000
Direction Départementale des Territoires du Doubs                   559d3813c751df392b390bd4  ckan      2020-05-12T16:00:58.661000
Do.TeRR . Géo-Centre                                                5a83f81fc751df6f8573eb8a  dcat      2023-05-02T16:47:26.133000
GRAND BESANCON METROPOLE                                            59196e9088ee38471c78dac6  ckan      2020-05-20T18:11:48.510000
Géo2France                                                          5ddc086f634f41190d4c1006  csw-dcat  2024-08-07T11:50:43.614000
GéoCompiégnois                                                      5bf29ad88b4c413977f828d7  ckan      2020-01-30T09:03:48.953000
Lig'Air                                                             5be949a9634f415deb46af0e  dcat      2024-01-31T09:37:14.948000
Office National des Forêts                                          534fff9ca3a7292c64a7803e  dcat      2023-02-03T21:30:36.203000
Oise Mobilité - Syndicat mixte des transports collectifs de l'Oise  5e874ace3af8a02435889f1b  ckan      2020-04-03T16:54:29.499000
Parc national de forêts                                             5f898bdf254e86297006ef0c  ckan      2020-12-01T13:53:58.370000
Parc naturel régional du Morvan                                     5f91506e6d1d6f595ceb0ea8  ckan      2020-12-16T08:19:25.188000
Région Bourgogne-Franche-Comté                                      5835cdb988ee383e0bc65bb3  ckan      2020-05-16T12:04:22.922000
Système d'Information sur l'Eau                                     534fffb2a3a7292c64a78123  csw-dcat  2024-06-07T15:21:36.103000
Système d'information sur la biodiversité                           653130edb6223421ef195862  csw-dcat  2024-06-04T08:22:48.950000
```

@Thesauruv On embarque quoi ?

**Comment by Thesauruv** [comment]
@streino 

Candidats sélectionnés (on en a déjà certains mais je les remets): 

Atmo Bourgogne-Franche-Comté
Cerema                                                              
DREAL Bourgogne-Franche-Comté
Direction Départementale des Territoires du Doubs
Do.TeRR . Géo-Centre
Géo2France
Lig'Air 
Office National des Forêts
Parc naturel régional du Morvan
Système d'Information sur l'Eau  
Système d'information sur la biodiversité

**Comment by Thesauruv** [comment]
J'ai évacué les organisations du type régions et métropoles, pour lesquelles il nous faudra un traitement spécifique.

**Comment by streino** [comment]
Mise à jour dans le cadre de #298.
Cf https://github.com/ecolabdata/ecospheres/issues/298#issuecomment-2346947772 pour le détail.
Les configs demo/prod seront également mises à jour en même temps que l'autre ticket.
