### ISSUE TITLE
Date de mise à jour d'un bouquet

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#273]
l'ensemble des bouquets sur https://demo.ecologie.data.gouv.fr/
comme sur ecologie.data.gouv.fr/ affichent respectivement une date de mise à jour il y à 7 et 6 jours. J'ai l'impression qu'il s'agit des dates de dernières mises en prod. Est ce possible de garder la date réelle de dernière mise à jour ?

**Comment by streino** [comment]
Je pense que c'est lié à la migration du schema des extras #243. C'était un one-shot, donc on ne devrait plus avoir ce problème, sauf à devoir refaire un jour une manip du même type.

@abulte sais-tu si on peut "forcer" une modif interne sans toucher à la date de màj ?

**Comment by abulte** [comment]
Yes c'est lié à la migration, et ça n'arrivera que dans ces cas là.

On ne peut pas éviter de toucher la date de modification, qui est la date interne de data.gouv.fr. On pourrait imaginer gérer une date de modification propre à Ecosphères dans les extras, mais il faudrait justifier cette modification non triviale.

**Comment by martyKN** [comment]
cc @Thesauruv pour la réponse

**Comment by streino** [comment]
> On ne peut pas éviter de toucher la date de modification, qui est la date interne de data.gouv.fr. On pourrait imaginer gérer une date de modification propre à Ecosphères dans les extras, mais il faudrait justifier cette modification non triviale.

À garder en tête le jour où une autre migration s'impose. On verra à ce moment là si l'ajout se justifie. D'ici là je propose de fermer le ticket si @martyKN tu es ok ?
