### ISSUE TITLE
Donnée archivée dans un bouquet : quel traitement ?

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#276]
Il y a une donnée sur le bouquet docurba dans demo.ecologie.data.gouv qui est affichée comme archivée mais qui n'est pas affichée comme non disponible. 
Vous en pensez quoi ? On fait disparaitre la fiche de MD ? On marque la donnée comme non dispo ?

![Capture d’écran 2024-07-16 à 09 47 05](https://github.com/user-attachments/assets/2cf63675-c3fd-44af-9b29-09826dd28c01)

**Comment by abulte** [comment]
Bonne question !

Déjà sur le contexte : on ne peut pas ajouter de jeu de données archivés à un bouquet, ils n'apparaissent pas dans le suggest (la liste de recherche). En revanche ils peuvent être archivés plus tard, notamment au moissonnage.

Si le jeu de données a été archivé, il est réputé non fiable (le cas nominal étant la suppression depuis le catalogue source au moissonnage), donc je pense qu'il faut le signaler. Le plus simple est peut-être de le traiter comme #221, donc "non disponible" avec un message explicatif dans l'accordéon.

**Comment by streino** [comment]
+1 à la proposition d'@abulte

**Comment by martyKN** [comment]
ok donc archivé = non dispo 
et je m'occupe de mettre un laïus à la main dans l'accordéon

**Comment by narduin** [comment]
Est-ce que je peux archiver un JDD moi-même pour tester ?

**Comment by streino** [comment]
> Est-ce que je peux archiver un JDD moi-même pour tester ?

Tu peux créer un dataset sur demo.data.gouv et en faire ce que tu veux. Affecte-le à l'orga [Ecosphères](https://demo.data.gouv.fr/fr/organizations/ecospheres/) comme ça la team data.gouv sait d'où ça vient.

**Comment by narduin** [comment]
> > Est-ce que je peux archiver un JDD moi-même pour tester ?
> 
> Tu peux créer un dataset sur demo.data.gouv et en faire ce que tu veux. Affecte-le à l'orga [Ecosphères](https://demo.data.gouv.fr/fr/organizations/ecospheres/) comme ça la team data.gouv sait d'où ça vient.

C'est ce que j'ai fait mais même avec le compte écosphères je n'ai pas trouvé comment archiver un dataset, seulement le passer en privé.

**Comment by abulte** [comment]
Effectivement ce n'est pas évident à trouver. Il n'y a pas d'interface sur data.gouv.fr pour archiver un jeu de données. C'est généralement le moissonneur qui archive les jeux de données.

Il faudrait soit :
- Retrouver le jeu de données de Martin dans son exemple si possible (attention les jeux de données archivés ne remontent pas dans la liste de recherche)
- ~~Demander à data.gouv.fr d'identifier quelques exemples (pas possible de filtrer sur ce cas dans l'API AFAIK)~~
- Archiver nous-mêmes un de nos jeux de données en mettant la date courante en ISO dans `dataset.archived` via l'API. Il vaut mieux rattacher le jeu de données à un bouquet de test avant de l'archiver, ce sera plus facile de le retrouver.

**Comment by abulte** [comment]
Autre possibilité pour en trouver : le détail d'un job pour un moissonneur affiche les jeux de données archivés.

<img width="414" alt="Capture d’écran 2024-08-27 à 12 07 05" src="https://github.com/user-attachments/assets/ce9e8379-8ddb-4724-b58b-f66a4e4dbc2a">


<img width="784" alt="Capture d’écran 2024-08-27 à 12 07 10" src="https://github.com/user-attachments/assets/f334b52b-9180-4cb9-b677-0a03a26c79e0">

https://demo.data.gouv.fr/fr/admin/harvester/666322daf23a13043384f012

Ex : https://demo.data.gouv.fr/fr/datasets/sup-ac1-perimetres-de-protection-des-monuments-historiques-dans-le-val-doise-2/ 

Il faudra certainement utiliser l'API pour rattacher ce jeu de données via son ID à un bouquet.

**Comment by narduin** [comment]
J'ai pu ajouter le dataset archivé en tant qu'url externe, il a été rattaché automatiquement 🙌

**Comment by narduin** [comment]
1. Ajouter un bouquet
2. Renseigner l'url d'un bouquet archivé
3. ex: https://demo.data.gouv.fr/fr/datasets/sup-ac1-perimetres-de-protection-des-monuments-historiques-dans-le-val-doise-2/

![Image](https://github.com/user-attachments/assets/0cfe228e-17d8-4049-a575-5c0a6a81fd72)
