### ISSUE TITLE
Bouquet invisible lors de l'ajout d'un jeu de données depuis la fiche du jeu de données.

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#277]
Depuis demo : je souhaite ajouter le jeu de données [PM4_Generateur_SUP](https://demo.ecologie.data.gouv.fr/datasets/66639fa55ed217bcd2e3595b) au bouquet sur[ l'élaboration ou évolution d'un document d'urbanisme.](https://demo.ecologie.data.gouv.fr/bouquets/elaboration-ou-evolution-dun-document-durbanisme-haute-savoie).

Je clique "Ajouter à un bouquet", le bouquet cible n'apparaît pas dans la liste déroulante.

![image](https://github.com/user-attachments/assets/3827765d-9b55-4ce1-bc35-d890bc145694)

**Comment by abulte** [comment]
Effectivement, on n'affiche que les bouquets directement rattachés au user courant, il faudrait également afficher :
- ceux de ses organisations
- tous les bouquets si on est admin

**Comment by Thesauruv** [comment]
@abulte merci pour le retour. Je suis connecté avec le compte Team Ecosphères qui est bien admin pourtant ?
