### ISSUE TITLE
Permettre à l'admin d'assigner un bouquet à une organisation

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#278]
Un agent de la métropole de Lyon a crée le bouquet de données sur le [calque de plantabilité](https://ecologie.data.gouv.fr/bouquets/calque-de-plantabilite) en son nom. Ce bouquet a vocation à être rattaché à l'organisation de la métropole de Lyon, comme cela a été fait pour le bouquet sur les [itinéraires de fraîcheur](https://ecologie.data.gouv.fr/bouquets/itineraires-fraicheur). Même besoin pour le bouquet sur [la coordination des projets relatifs aux toitures parisiennes](Coordination des projets relatifs aux toitures parisiennes).

En tant qu'admin, nous souhaitons pouvoir réaliser ce changement depuis la page d'édition d'un bouquet.

**Comment by abulte** [comment]
@Thesauruv tu voudrais ça rapidement ou ça peut attendre l'arrivée de Nicolas ? Ca peut être un bon sujet à traiter à son arrivée, pas trop compliqué.

Implémentation proposée :
- ajouter un bloc visible seulement aux admins dans la page d'édition d'un bouquet
- y ajouter un sélecteur avec autocomplétion branché sur le suggest des organisations de data.gouv.fr 
- permettre de sélectionner n'importe quelle organisation et l'assigner au bouquet
- à voir : traitement à apporter au bloc "standard" de gestion du propriétaire dans le cas des admins : ne pas l'afficher, le laisser inopérant si une organisation "admin" est sélectionnée, le désactiver...

**Comment by Thesauruv** [comment]
@abulte ça peut effectivement attendre l'arrivée de Nicolas !

**Comment by DanFluture275** [comment]
@narduin L'autosuggest présente des soucis sur les pages admin/bouquets/add et admin/bouquets/edit/
![Image](https://github.com/user-attachments/assets/d7a1d410-2584-4384-a4a8-93e4181306c7)

**Comment by narduin** [comment]
> [@narduin](https://github.com/narduin) L'autosuggest présente des soucis sur les pages admin/bouquets/add et admin/bouquets/edit/

C'est résolu normalement @DanFluture275, tu peux retester !
https://github.com/opendatateam/udata-front-kit/pull/516#issuecomment-2374670034
