### ISSUE TITLE
Accéder à la fiche de métadonnées source

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#288]
Depuis la page d'un jeu de données, le renvoi vers la fiche de métadonnées source semble na pas être implémenté dans ecologie.data.gouv, bien que disponible dans data.gouv.

**Exemple sur data.gouv**
![image](https://github.com/user-attachments/assets/5ff8deb4-cb74-4df1-a93e-47916f41e033)

**Comment by abulte** [comment]
- vérifier sur datagouv/components si il n'y a pas un petit composant "lien externe"
- sinon utiliser `harvest_extras.remote_url` pour afficher l'encart
