### ISSUE TITLE
Meta ticket - Page d'accueil ecologie.data.gouv

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#293]
Dans la version actuelle d'ecologie.data.gouv, les utilisateurs manquent de visibilité sur "l'offre de service". Ils ne comprennent pas par exemple que : 
- ils peuvent spontanément (c'est-à-dire sans que l'initiative vienne de l'équipe Ecosphères) initier ou cloner un bouquet pour documenter leurs objectifs et travailler de manière collaborative au renseignement des facteurs et des jeux de données associés
- ils peuvent nous soumettre des catalogues qui mériteraient d'être moissonnés par data.gouv pour réexposer leurs données dans les bouquets
- ils peuvent nous solliciter pour organiser des groupes de travail sur la thématique d'un bouquet (point à valider lors du comité de pilotage du 02/09) dans une optique de veille ou de déploiement national de leur service

Inspirations :
- https://conseillers-entreprises.service-public.fr/
- https://monespacecollectivite.incubateur.anct.gouv.fr/
- https://www.georisques.gouv.fr/
- https://ecobalyse.beta.gouv.fr/

Je trouve tout particulièrement intéressante la page d'accueil de l'outil [Conseillers-Entreprises ](https://conseillers-entreprises.service-public.fr/) qui présente sous formes de cartes les besoins et actions possibles des utilisateurs via cet outil.

Liste des tickets pour la refonte de la home : 

- [x] #390
- [x] #391
- [x] #392
- [x] #393
- [x] #394
- [x] #395
- [x] #399 
- [x] #396
- [x] #397

**Comment by ghost** [comment]
Version finale de la homepage : https://www.figma.com/design/goZNoxBnPfhh8awXjnDzY6/Maquettes-2024?node-id=198-8146&node-type=section&t=jxWSHBX1OugvuPOk-11

**Comment by at-github** [comment]
Hello @thomas-duport & @DanFluture275, j'ai fait une demande d'accès au figma avec mon mail multi.coop

**Comment by ghost** [comment]
Hello @at-github ! Demande d'accès validée bon courage à toi
