### ISSUE TITLE
Superposition involontaire dans la modale sélection de jeux de données

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#294]
> En revanche, ça se superpose à "Entrée pour sélectionner" qui se superpose lui-même d'habitude au titre du jeu de données (peut-être une issue à créer ?)

![image](https://github.com/user-attachments/assets/965f3b04-2669-499b-b42d-d94bab408961)

_Originally posted by @narduin in https://github.com/opendatateam/udata-front-kit/issues/507#issuecomment-2310052368_

**Comment by narduin** [comment]
Le plus simple consisterait à passer cet élément en bas de la carte pour éviter qu'il masque autre chose. L'incovénient étant qu'on a un petit layout shift à l'affichage.

![Image](https://github.com/user-attachments/assets/34cb7b71-7331-44ce-ba59-68908fb68c82)

Ceci dit, je ne sais pas s'il est utile de l'afficher car à la souris, pas besoin et au clavier c'est un comportement attendu. On pourrait le passer en `sr-only` pour les lecteurs d'écran je pense.

**Comment by streino** [comment]
Assez d'accord pour le cacher par défaut, sauf lecteurs d'écran (ne connaissant pas les comportements attendus sur ces devices).
