### ISSUE TITLE
Moissonneurs GeoIDE tests sur demo

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#301]
DDT a minima + voir [autres endpoints](https://snum.gitlab-pages.din.developpement-durable.gouv.fr/ds/gsg/api-geoide/api-geoide-docs/api-geoide-services-csw-url-acces/#points-de-moissonnage)

**Comment by streino** [comment]
@Thesauruv @benoitdavidfr 
J'ai listé les endpoints dispos ici : https://grist.incubateur.net/o/ecospheres/u4V9KZ7tr6Rd/geoide-endpoints/p/2
J'ai annoté quand je savais, je vous laisse compléter ?

**Comment by Thesauruv** [comment]
@streino merci ! J'ai également ajouté en "oui" les _directions interdépartementales des routes_ et la _Direction régionale et interdépartementale de l'Hébergement et du Logement_

**Comment by streino** [comment]
Quelques moissonneurs ARA en place sur demo : https://demo.data.gouv.fr/fr/organizations/?q=ecospheres-test.

Pour calculer le "potentiel de nouvelles fiches" GeoIDE, j'ai plutôt directement requêté les endpoints CSW GeoIDE de la liste Grist ci-dessus, en filtrant sur type=dataset.

@Thesauruv Ça nous donne un total de 26452 fiches supplémentaires. Le détail est dans Grist.

**Comment by Thesauruv** [comment]
@streino merci ! Intéressant de voir que certains endpoints ne sont associés à aucun jeu de données. Je suppose que le premier moissonnage sera lancé dans la nuit.

**Comment by streino** [comment]
> Je suppose que le premier moissonnage sera lancé dans la nuit.

Non tous ont déjà tourné hier. Je pense que c'est parce que les fiches existent déjà sur demo.data.gouv, et dans ce cas, la fiche reste rattachée à l'orga qui l'a moissonnée en premier.

Par exemple, https://demo.data.gouv.fr/fr/organizations/ecospheres-test-ddt74/ n'a pas beaucoup de fiches car https://demo.data.gouv.fr/fr/organizations/direction-departementale-des-territoires-de-haute-savoie/ était là avant.

Ça va être compliqué de régler ça sans interagir avec les propriétaires d'orgas. Je voudrais pas leur "piquer" des fiches pour nous tests sans leur accord. Mais ça devrait se régler naturellement pendant la phase de déploiement.

**Comment by Thesauruv** [comment]
Ok, merci 👍 Je te propose qu'on creuse ce sujet pour identifier potentiellement certains risques en phase de déploiement.

**Comment by streino** [comment]
Ça marche, en attendant je ferme ce ticket, rien de plus à faire au niveau branchements.

**Comment by streino** [comment]
Pardon, je ne ferme pas, je passe en "To test" ;)
