### ISSUE TITLE
Questionnaire suite webinaire moissonnage

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#303]
Dans un premier temps, lister les questions à inclure et déterminer le timing d'envoi.

ping @Thesauruv

**Comment by streino** [comment]
@Thesauruv @alhyss @benoitdavidfr @abulte 

J'ai commencé un pad pour le questionnaire moissonnage destiné aux gestionnaires de catalogue : https://pad.numerique.gouv.fr/qJNw8ObsRQm-lASdEw3OFA?both

N'hésitez pas à ajouter des questions ou commenter celles qui sont déjà listées (comme d'hab, initiales en pré/suf-fixe "[GR]" pour pouvoir suivre).

**Comment by DanFluture275** [comment]
ping @Thesauruv : peux-tu regarder rapidement si tu as des quetsions supplémentaires pour qu'on puisse envoyer le formulaire.

**Comment by Thesauruv** [comment]
@DanFluture275 @streino Je viens de commenter brièvement.

**Comment by streino** [comment]
Merci @Thesauruv. Il me semble que tu avais en tête des questions, elles y sont déjà ou tu envisages de refaire une passe ?

Quand au timing d'envoi du questionnaire, deux possibilités : 
1. ASAP pendant que c'est encore frais et pour avoir de la visibilité au plus tôt.
2. En même temps que la mise à dispo de la doc/outils, en espérant des réponses plus informées.

**Comment by abulte** [comment]
Je vote ASAP 😄 🗳️

**Comment by Thesauruv** [comment]
@streino @abulte @DanFluture275 Je suis également pour l'envoie ASAP du questionnaire, avec la vidéo du wébinaire. On fera autre mail pour l'envoi de la doc et des outils.

@streino Le questionnaire couvre bien ce que j'avais à l'esprit !

**Comment by DanFluture275** [comment]
Questionnaire envoyé le 23/09
--> https://tally.so/forms/mKDy8k
