### ISSUE TITLE
Communication auprès des ADL avant publication des données GéoIDE

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#314]
- [x] Informer GeoIDE [Benoît]
- [x] Déploiement en démo des moissonnages GéoIDE [Gabriel] https://github.com/ecolabdata/ecospheres/issues/357
- [x] Informer les ADL de la mise en production la semaine du 11/11 des données GéoIDE, de la disponibilité des données GéoIDE sur démo (coordination avec Gabriel), du besoin d'actualisation de leurs organisations : nommage, administrateur, éventuellement déclaration autonome du point de moissonnage avant la semaine du 11/11. [Benoît]
- [x] Proposer des créneaux de permanence pour réponse à leurs questions [Gabriel, Benoît].

Liste de diffusion : 
- [labo.add.dreal@developpement-durable.gouv.fr](mailto:labo.add.dreal@developpement-durable.gouv.fr)
- [labo.add.ddt@developpement-durable.gouv.fr](mailto:labo.add.ddt@developpement-durable.gouv.fr) 

Suggestion de Leslie et de Julien Lardemer : mettre en copie les chefs de pôles SIG et les chefs des services connaissances.

**Comment by streino** [comment]
Related #212

**Comment by Thesauruv** [comment]
@streino un échange avec la DDT 95 est-il prévu ? Enjeu d'avoir le go d'une première DDT.

**Comment by streino** [comment]
Je prévois de reprendre contact avec eux dès qu'on a le dashboard superset et que j'ai pu faire une première vérification du moissonnage sur demo. Normalement d'ici la fin de semaine donc.

**Comment by streino** [comment]
Cf [CR du point DDT 95](https://github.com/ecolabdata/ecospheres/issues/261#issuecomment-2423904814) => On devrait être bon pour passer à l'échelle.

**Comment by streino** [comment]
Dashboards par orga (cf #398) : https://grist.numerique.gouv.fr/o/ecospheres/j82pNr1yf51g/Endpoints/p/4

**Comment by benoitdavidfr** [comment]
message envoyé comme prévu le 24/10/2024
