### ISSUE TITLE
Chart Jeux de données - Liste

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#321]
**Nom du chart :** Jeux de données - Liste
**Format :** tableau
**Colonnes :** Titre, Id jeu de données, date de création, date de modification

**Comment by DanFluture275** [comment]
- La liste des JDD avec titre, dates creation/modification et nombre de distributions est en MUST.
- Les liens externes renvoyant vers data.gouv et fiche source peuvent être traités dans un 2e temps. En attendant, afficher l'ID du dataset.

@streino qu'entends-tu par nombre de distributions ?

**Comment by at-github** [comment]
Je veux bien une courte explication de _JDD_ svp

**Comment by streino** [comment]
- JDD = jeu de données = dataset. Un JDD = une URL https://www.data.gouv.fr/fr/datasets/xxx.
- distribution = une représentation spécifique sous laquelle le JDD est distribué (un fichier zip, un flux, ...). Les distributions sont listées sous l'onglet "Fichiers" sur data.gouv.
