### ISSUE TITLE
Charts Temporel

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#325]
- [x] **Nom du chart :** Disponibilité date de création
**Format :** Pie chart
**Valeur :** Date de création présente / Date de création non renseignée

- [x] **Nom du chart :** Disponibilité date de modification
**Format :** Pie chart
**Valeur :** Date de modification présente / Date de modification non renseignée

- [x] **Nom du chart :** Cohérence dates création - modification
**Format :** Pie chart
**Valeur :** Date cohérentes / Date non cohérentes

**Comment by DanFluture275** [comment]
- Les indicateurs de présence (camemberts) et de cohérence pour les dates de création/modification sont en MUST.
- L'affichage sous forme de graph temporel peut être fait dans un 2e temps.
- La gestion de la fréquence et couverture temporelle sont basse prio (à rediscuter d'ici là).

**Comment by at-github** [comment]
En attente que la "moulinette" tourne avec la pr mergée https://github.com/ecolabdata/ecospheres-dashboard-backend/pull/1

**Comment by abulte** [comment]
@at-github c'est fait depuis hier soir https://github.com/ecolabdata/ecospheres/issues/332#issuecomment-2375045080

**Comment by at-github** [comment]
> [@at-github](https://github.com/at-github) c'est fait depuis hier soir [#332 (comment)](https://github.com/ecolabdata/ecospheres/issues/332#issuecomment-2375045080)

Ok il a fallut lancer une synchro côté superset pour pouvoir voir les nouvelles colonnes
