### ISSUE TITLE
Intégration du dashboard patrimoine sur ecologie.data.gouv

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#328]
En tant qu'utilisateur du site ecologie.data.gouv.fr, je souhaite pouvoir accéder aux indicateurs de qualité du moissonage.

- Ajouter dans la page "à propos", dans le paragraphe "Quelles données sont mises à disposition ?" un lien vers le dashboard patrimoine.
- Texte : 

Un [gestionnaire de patrimoine](https://dashboard.data.developpement-durable.gouv.fr/superset/dashboard/gestionnaire-patrimoine-prod/?standalone=2) a été mis en place pour permettre de visualiser le patrimoine d'une organisation moissonnée par data.gouv.fr.
Il s'adresse principalement aux gestionnaires de catalogue et administrateurs de données locales, et a pour objectif de faciliter l'identification d'éventuels problèmes de qualité des métadonnées.

- Au clic sur le lien, afficher dans un nouvel onglet le tableau de bord de production : `https://dashboard.data.developpement-durable.gouv.fr/superset/dashboard/gestionnaire-patrimoine-prod/?standalone=2`

Ajouter également un laïus sur Isomorphe / revoir le paragraphe pour mieux expliquer le moissonage. @streino 

Note pour plus tard : à terme une intégration dans la page organisation devra être envisagée.

**Comment by abulte** [comment]
https://github.com/opendatateam/udata-front-kit/pull/497
