### ISSUE TITLE
Mise en place du drill down

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#329]
Résolution du bug sur le drill down sur les charts actuels. A priori lié au fait que les charts sont sur les vues avec jointure

**Comment by DanFluture275** [comment]
Toujours d'actu ? (drill down natif si tous les charts s'appuient bien sur la même base)

**Comment by at-github** [comment]
Liste des problèmes :
- [x] Chart : "Jeux de données - liste", cliquer sur "URL data.gouv" -> `Error: column "URL data.gouv" does not exist…`
- [x] Chart : "Préfixe ID source - liste", cliquer sur "id" -> `Error: column reference "id" is ambiguous
`

**Comment by at-github** [comment]
ID source - présence réparé (il consultait un autre modèle)
