### ISSUE TITLE
Reprise des traitements custom metabase dans la moulinette d'import de base

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#332]
Doc des champs datagouv : https://doc.data.gouv.fr/moissonnage/dcat/#autres-m%C3%A9tadonn%C3%A9es
Créer  / compléter les nouvelles colonnes dans la base lors de l'import, afin de pouvoir construire le dashboard superset en se basant sur la base Postgre, sans avoir à faire de calculs supplémentaires dans superset : 
 
Tous les champs type "présence" sont déjà crées via la moulinette et présents dans la base : 
- Id source, fréquence, date, distributions présent etc...

Champs à créer dans la moulinette : 
- Préfixe ID source : Harvest Extras → Remote ID : Normalement, url du catalogue + id du jeux de données.
**Traitement à faire :**  Récupérer la partie url du catalogue (ce qu'il y a avant le dernier slash).
**Objectif métier :** vérifier que les remote ID sont cohérents au sein d'un catalogue donné, et identifier lorsqu'il n'y a pas de préfixe.
- Préfixe URL source : Harvest Extras → Remote URL : Normalement, une page HTML qui pointe sur la fiche de métadonnées du catalogue source (dans l'idéal identique à ID source)
**Traitement à faire :**  Récupérer la partie url du catalogue (ce qu'il y a avant le dernier slash).
**Objectif métier :** vérifier que les remote URL sont cohérents au sein d'un catalogue donné, et identifier lorsqu'il n'y a pas de préfixe.
- URL data gouv : concaténation simple pour avoir un lien cliquable
- Date cohérente (>=) et couverture temporelle cohérente (>)

PR (draft pour l'instant) : https://github.com/ecolabdata/ecospheres-dashboard-backend/pull/1

**Comment by at-github** [comment]
Peut on avoir un peu plus de précision concernant : "Date cohérente" & "couverture temporelle cohérente" (colonne de la table, règle…) @DanFluture275 ?

**Comment by abulte** [comment]
- Dates cohérentes :

Dans metabase : `case(isempty([Harvest Extras → Modified At]), True, [Harvest Extras → Created At] <= [Harvest Extras → Modified At])`

Traduction : si pas de `harvest_extras.modified_at`, oui sinon vérifier que `harvest_extras.modified_at ` >= `harvest_extras.created_at `

- Couverture temporelle cohérente :

Metabase = `case([Temporal Coverage → Start] < [Temporal Coverage → End], True, False)`

Traduction : vérifier que `temporal_coverage.start` < `temporal_coverage.end`. Voir comment ça se comporte quand pas de couverture temporelle, je mettrais oui dans ce cas.

**Comment by at-github** [comment]
Au niveau où mon code s'intercale, dans `['harvest']` je n'ai que `last_update`, je pioche donc à la racine du payload, est-ce cohérent avec le résultat attendu ?

**Comment by streino** [comment]
[Ces MDs sont tricky](https://github.com/abulte/ecospheres-datagouvfr-metadata/blob/main/ecospheres-datagouvfr-metadata.md#dates-de-re%CC%81fe%CC%81rence), donc on garde exactement les mêmes. Il se peut qu'elles soient manquante, dans ce cas c'est None.

**Comment by abulte** [comment]
On a bien du `harvest['modified_at']` assez souvent, si j'ai bien compris la question.

```
demo=# SELECT count(distinct(harvest_extras->'modified_at')) from catalog;
 count
-------
  1272
(1 row)

```

**Comment by at-github** [comment]
> On a bien du `harvest['modified_at']` assez souvent, si j'ai bien compris la question.
> 
> ```
> demo=# SELECT count(distinct(harvest_extras->'modified_at')) from catalog;
>  count
> -------
>   1272
> (1 row)
> ```


```python
    def get_consistent_date(self):
        print(self.payload['harvest'])
        …
```

```
{'backend': 'DCAT', 'source_id': '6284de618aae1dfc6e547a61', 'remote_id': 'pci18_borne https://catalogue.doterr.fr/geonetwork/srv/cb143e0f-c0f2-49fa-a31d-744bb1938876', 'domain': 'ca
talogue.doterr.fr', 'last_update': '2024-09-13T17:19:57.362000+00:00', 'uri': 'https://catalogue.doterr.fr/geonetwork/srv//datasets/pci18_borne https://catalogue.doterr.fr/geonetwork
/srv/cb143e0f-c0f2-49fa-a31d-744bb1938876', 'dct_identifier': 'pci18_borne https://catalogue.doterr.fr/geonetwork/srv/cb143e0f-c0f2-49fa-a31d-744bb1938876'} 
```

**Comment by abulte** [comment]
Oui, assez souvent, mais pas toujours. Ex : https://demo.data.gouv.fr/api/2/datasets/66bd4fe809c8aa3c089b64a0/.

**Comment by at-github** [comment]
@DanFluture275 je copie / colle le même message que dans slack :
> Désolé Dan, j'ai mergé ma pull request, j'imagine que du coup je respecte pas la procédure.
Étant donné que c'était un "ticket technique" sans vraiment de résultat visible d'un utilisateur, est-ce qu'on est pas dans l'exception :ange:  ?
Que souhaites-tu comme status sur le ticket du coup ?

**Comment by abulte** [comment]
J'ai fait tourner le script, le résultat devrait être visible via https://dashboard.ecospheres.france.sh/.
