### ISSUE TITLE
Contrastes des textes hors boutons

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#333]
Paragraphe 7.1 du rapport d'audit : [Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
**Sévérité : majeur**

**Todo** :

- [x] Contraste texte par défaut rechercher dans les champs de saisie --> reprendre la même que dans le champs de recherche principal qui est ok à priori --> chez nous
- [x] Tag tertiaire --> @thomas-duport préciser le design pour cet élément. Attention, il y a d'autres couleurs pour d'autres catégories qui posent sans doute aussi problème --> chez nous

**Comment by ghost** [comment]
Done @narduin tu retrouveras les tags [ici](https://www.figma.com/design/goZNoxBnPfhh8awXjnDzY6/Maquettes-2024?node-id=83-8125&t=EYaTHRodkrNRR1nw-4)
