### ISSUE TITLE
Gestion des changements de page

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#334]
Paragraphe 9 et 10.1 du rapport d'audit : [Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
**Sévérité : bloquant**

Les changements de page n'entraînent pas de rechargement par le navigateur. Le lecteur d'écran n'a donc aucun moyen d'avertir l'utilisateur.

**Todo :** 
- Observer les routes et rammener à chaque changement de page le focus sur le skip link. (invisible par défaut)

Adapter la solution proposée dans l'audit : 

Après le déclenchement d'un lien ou d'un bouton et le chargement d'une page :

- L'élément <title> de chaque page est modifié (cf <title> des pages)
- le focus est déplacé au début de l'élément <body> :
    - pour chaque page, après l'élément <body> :
    - ajouter un paragraphe `<p class="sr-only" tabindex="-1">XXX</p>`, où XXX reprend exactement
le titre `<title>` de la page
        - l'attribut `tabindex="-1"` permet à un élément non
interactif de recevoir le focus via js
        - ce `<p>` est masqué visuellement en utilisant la classe
css sr-only
    - Utilisez la fonction `js focus()` pour déplacer le focus sur cet
élément `<p>`

**Comment by narduin** [comment]
@DanFluture275 tu peux review !
(je ne sais pas si tu as une notif quand je change le status de l'issue)
