### ISSUE TITLE
Alt vide pour les images décoratives

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#339]
Paragraphe 7.11 du rapport d'audit : [Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
**Sévérité : majeur**

Todo : Ajouter un attribut alt vide (`alt=””`) dans tous les éléments `<img>` des images décoratives.

- [x] P01 - Accueil
- [x] P07 - Bouquets
- [x] P08 - Dataset
- [x] P09 - Détail Bouquet
- [x] P11 - Bouquet (après connexion)

Pour les images svg décoratives
- [x] Ajouter à chaque image <svg> décorative un attribut` aria-hidden="true"` (

**Comment by narduin** [comment]
@DanFluture275, j'ai mergé directement. C'est principalement des ajouts d'attributs dans le code, est-ce que tu veux review malgré tout?
