### ISSUE TITLE
Correction langue du document

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#341]
Paragraphe 8.2 du rapport d'audit : [Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
**Sévérité : majeur**

Todo :
Remplacer le code de la langue par fr
`<html lang="fr">`

**Comment by narduin** [comment]
J'avais profité [d'une issue sur l'indexation](https://github.com/opendatateam/udata-front-kit/pull/508/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R2) pour corriger ce problème :)
