### ISSUE TITLE
Créer une page plan du site

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#343]
Paragraphe 8.4 du rapport d'audit : [Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
Sévérité : **majeur**

Todo : 

- [x] @thomas-duport : préparer le design de la page, en ne référençant que les contenus de niveau 1.
- [ ] dév de la page, attention à l'automatisation
- [x] Ajouter le lien vers cette page dans le footer

**Comment by ghost** [comment]
Done @narduin tu retrouveras les pages [ici](https://www.figma.com/design/goZNoxBnPfhh8awXjnDzY6/Maquettes-2024?node-id=83-8177&t=EYaTHRodkrNRR1nw-4)
