### ISSUE TITLE
Lien de déconnexion

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#344]
Paragraphe 10.5 du rapport d'audit : [Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
Sévérité : **majeur**

Todo :

Ajouter un texte se déconnecter pour que ce soit plus explicite --> @thomas-duport préparer design

**Comment by ghost** [comment]
Done côté design
@narduin : tu peux retrouver le composant [ici](https://www.figma.com/design/goZNoxBnPfhh8awXjnDzY6/Maquettes-2024?node-id=83-8088&t=EYaTHRodkrNRR1nw-4)
