### ISSUE TITLE
Contraste des textes dans les boutons

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#345]
Paragraphe 7.1 du rapport d'audit : [Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
Sévérité : **majeur**
- [x] Couleur hover des boutons (#5982E0) à remplacer --> @thomas-duport préciser la couleur de remplacement --> upstream coté data.gouv. Possible de le surcharger en attendant le fix

**Comment by DanFluture275** [comment]
Fait via sucharge CSS

**Comment by ghost** [comment]
@narduin sujet traité
Tu peux le retrouver ici : https://www.figma.com/design/goZNoxBnPfhh8awXjnDzY6/Maquettes-2024?node-id=277-8707&node-type=frame&t=X6S9o1hA74U5Huq3-11

J'ai proposé 2 choses :
- Un hover qui répond aux normes d'accessibilité avec le bleu primaire existant
- Une proposition avec le bleu du DSFR
