### ISSUE TITLE
Dashboard moissonnage : date de dernier moissonnage invalide ?

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#359]
En base on récupère 20/9

```
dashboard_backend=# select max((harvest_extras->'last_update')::text) from catalog where deleted is false;
                max
------------------------------------
 "2024-09-20T04:10:15.342000+00:00"
```

Sur le dashboard on affiche 19/9

![Image](https://github.com/user-attachments/assets/d6683843-8c98-4838-8603-925024efbb77)

**Comment by DanFluture275** [comment]
Ajouter un max dans la requete

**Comment by at-github** [comment]
`max` ajouté. Ce jour, la modification n'est pas visible
