### ISSUE TITLE
Reprise onglet Distribution

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#361]
Reprendre l'onglet “Distributions” du dashbboard metabase DDT 95, sauf le chart "Format de distribution - liste"
Voir si ça ne pête pas le drill down et comment il se comporte car données issues d'une table différente, sinon à mettre dans dashboard séparé.

**Comment by at-github** [comment]
Je n'arrive pas à avoir un graphique ferré à droite sans contenu à gauche

**Comment by at-github** [comment]
@abulte @streino

Concernant le tableau "Jeux de données avec distributions - liste"

Je n'arrive pas à avoir le même résultat que sur metabase.
Sur ce dernier, les titres semblent uniques, mais je vois rien dans metabase qui force cette condition.
Également j'ai ~ 3700 page de 10 résultats au lieu de 2000 (metabase)

J'ai bien une jointure catalog <-> resources et un filtre deleted = false

**Comment by abulte** [comment]
> J'ai bien une jointure catalog <-> resources

Sur quels champs ?

**Comment by at-github** [comment]
Jointent sur dataset_id comme je le distingue sur metabase

**Comment by at-github** [comment]
Concernant le tableau "Format de distribution - liste"

Il faudrait implémenter le format `<suspect>` dans la _moulinette_

**Comment by abulte** [comment]
```
dashboard_backend=# select count(distinct(dataset_id)) from resources;
 count
-------
  5328
(1 row)
```

C'est à peu près ça qu'on devrait avoir pour une liste de jeux de données avec distribution, non ? PI le count est le même sur la base de données utilisée par metabase.

**Comment by streino** [comment]
> Concernant le tableau "Format de distribution - liste"
> 
> Il faudrait implémenter le format `<suspect>` dans la _moulinette_

Non car cf description : 

> sauf le chart "Format de distribution - liste"

**Comment by abulte** [comment]
Il te manque les group by de Metabase

<img width="452" alt="Capture d’écran 2024-10-02 à 15 14 17" src="https://github.com/user-attachments/assets/7c96b73d-b211-464d-9530-997c67ed3bbf">

**Comment by at-github** [comment]
> > Concernant le tableau "Format de distribution - liste"
> > Il faudrait implémenter le format `<suspect>` dans la _moulinette_
> 
> Non car cf description :
> 
> > sauf le chart "Format de distribution - liste"

Merci

**Comment by at-github** [comment]
> Il te manque les group by de Metabase
> 
> <img alt="Capture d’écran 2024-10-02 à 15 14 17" width="452" src="https://private-user-images.githubusercontent.com/119625/372875591-7c96b73d-b211-464d-9530-997c67ed3bbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDA3NDUsIm5iZiI6MTcyNzk0MDQ0NSwicGF0aCI6Ii8xMTk2MjUvMzcyODc1NTkxLTdjOTZiNzNkLWIyMTEtNDY0ZC05NTMwLTk5N2M2N2VkM2JiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QwNzI3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzE1YTU5YjBiMDEyM2FhMjhiZTg2N2I2Yjk0MDFkODUzYzBiNDhjNmViYWZhZWYwODBlNmY4NDJkNmVlMWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HqVETb6mau8WzmgkChQqJKKdMtI-WDFJUEgg3j7Zfq8">

Merci @abulte !
Je suis arrivé à mettre le même `group by` mais dans un nouveau dataset… ce qui n'est pas l'idéal, ce graphique ne répondant plus au _drill down_. Je vais creuser pour voir comment faire un group by dans le chart pltuôt que le dataset…

**Comment by abulte** [comment]
A vue de nez, tu peux utiliser seulement la table `catalog` pour ce graph, vu que tu as `nb_resources` dedans.

**Comment by at-github** [comment]
C'est bon maintenant avec un peu de bidouille. Maintenant, même en ayant tout les charts de cet onglet avec le même dataset, le drill down ne fonctionne qu'avec le camembert "Label de distribution - présence"

**Comment by at-github** [comment]
Je tente de traiter tout les problèmes de drill down dans le ticket dédié #371 au lieu de bloquer celui-ci

**Comment by DanFluture275** [comment]
@at-github Le filtre par organisation ne fonctionne pas

**Comment by at-github** [comment]
> [@at-github](https://github.com/at-github) Le filtre par organisation ne fonctionne pas

C'est fixé. La colonne `name` de la table organisation n'était pas dans le select du dataset (je ne mets pas systématiquement toutes les colonnes). C'est ajouté désormais et tous les charts réagissent au filtre organisation
