### ISSUE TITLE
Vue détaillée des méta d'un JDD

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#362]
Dans le chart liste des jeux de données, ajouter une colonne "Métadonnées brutes" renvoyant vers l'objet JSON data.gouv.
Nouvelle colonne à ajouter dans la moulinette.

**Comment by streino** [comment]
Sur Metabase c'est pas vraiment un widget qui est utilisé, mais le "comportement du clic" (éditer le dashboard, puis "comportement du clic" sur le widget de liste des jeux de données) pour la colonne "Title" qui redirige vers une URL custom de type `https://ecospheres-catalog.app.france.sh/public/dashboard/8ec4fb6f-94da-4941-bb15-bcac66234abd?id={{dataset_id}}#hide_parameters=id`.

J'ai pas l'impression qu'il y ait une vue équivalente sur Superset, donc l'API data.gouv semble plus plus simple ?

Appel API pour afficher les métadonnées d'un dataset : 
https://demo.data.gouv.fr/api/1/datasets/5ce2a5a4634f415cf996eb50/

**Comment by abulte** [comment]
Peut-être api v2 pour plus de concision https://demo.data.gouv.fr/api/2/datasets/5ce2a5a4634f415cf996eb50/

**Comment by streino** [comment]
Si on renvoie vers l'API data.gouv plutôt qu'une "jolie" vue détaillée, ça pourrait être pas mal de faire une nouvelle colonne type "API data.gouv" plutôt que de mettre le lien sur le titre ?

**Comment by DanFluture275** [comment]
J'ai pu le faire via une regex dans la requete SQL. Du coup, je sais pas si ça a un interêt de le mettre dans la moulinette...
