### ISSUE TITLE
Identification des données "calculées"

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#363]
Encadrer systématiquement avec < et > les données calculées type : 
`<préfixe manquant>, <suspect>`, etc...

**Comment by DanFluture275** [comment]
done pour préfixe manquant directement dans le requete custom SQL

**Comment by at-github** [comment]
Je me trompe ou tu l'as géré toi même @DanFluture275 ?

**Comment by DanFluture275** [comment]
Oui, je l'ai géré pour "préfixe manquant". Et comme on ne reprend pas le chart Format de distribution - liste, pas besoin de gérer le cas "supect" pour le moment. Je clos le ticket

**Comment by streino** [comment]
Juste pour être sûr, la partie qui assigne "préfixe manquant" et la partie qui met entre "<...>" est bien gérée au même niveau ? C'est dans le SQL plutôt que dans la moulinette ?

**Comment by DanFluture275** [comment]
Oui, c'est pour le moment dans la requête SQL de la dimension du chart

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/40dc4810-8c99-48be-9214-f635590559a0">

**Comment by streino** [comment]
Ce serait préférable de gérer ça au niveau moulinette, là c'est plutôt de l'ordre du hack. Donc IMO à réouvrir.
