### ISSUE TITLE
Traduction libellés de licences

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#364]
Bloc Licences : Récupérer et afficher les libellés plus clairs associés aux types de licences.
Todo : 
Dans la moulinette : 
- faire un appel API vers https://demo.data.gouv.fr/api/1/datasets/licenses/ et récupérer les mapping
- ajouter une colonne licence_label
- utiliser cette colonne dans le chart licence list.

**Comment by streino** [comment]
Liste des licences via l'API data.gouv : https://demo.data.gouv.fr/api/1/datasets/licenses/
