### ISSUE TITLE
Ouverture liens nouvelle fenêtre

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#368]
Paragraphe 11.1 et 14.2 du rapport d'audit : [Rapport Audit RGAA 4.1.2 - ECOSPHERES.pdf](https://github.com/user-attachments/files/17028986/Rapport.Audit.RGAA.4.1.2.-.ECOSPHERES.pdf)
Sévérité : **majeur**

Les liens qui s'ouvrent dans une nouvelle fenêtre doivent l'indiquer préalablement à l'utilisateur.
Ajouter un attribut title qui reprend le contenu du lien + ' - nouvelle fenêtre'.

- [ ] footer
- [ ] lien externes avec icones

**Comment by narduin** [comment]
Pour les liens du footer il faut mettre à jour `vue-dsfr` au moins vers 6.2, ce qui veut dire gérer les "breaking changes" de la [v6.0.0](https://github.com/dnum-mi/vue-dsfr/releases/tag/v6.0.0)
