### ISSUE TITLE
Bug drill down depuis les listes

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#371]

**Comment by at-github** [comment]
Piste 2 : Ce n'est pas tout à fait vrai pour tous les charts, mais il est possible que les tables en mode agrégations posent problèmes

**Comment by at-github** [comment]
Piste 1 : les colonnes basées sur du json posent problème
Contre exemple -> Chart "License liste" interroge "license" de la table "catalog"

**Comment by at-github** [comment]
Sortir une valeur contenue dans un json dans une colonne pré-calculée débloque au moins 1 cas
