### ISSUE TITLE
Modifier le comportement des champs de filtre

### ISSUE THREAD

**Issue by narduin** [ecolabdata/ecospheres#374]
Actuellement lorsque l'on filtre des datasets ou des bouquets via la recherche textuelle, la page s'actualise immédiatement (ou après un délai de 400ms).
L'interface est actualisée à chaque fois, les `title` et le nombre de résultats sont mis à jour et annoncés.

Pour certains utilisateurs, 400ms est un délai très court. C'est également problématique lorsque l'on souhaite corriger une erreur dans sa saisie.
Afin d'éviter des changements d'interfaces trop fréquents et des annonces intempestives, il faudrait allonger le délai de 400ms pour plus long.
Cependant, un délai plus long donne l'impression que le site bug ou est lent.

Une solution serait de déclencher le filtrage à la validation utilisateur. C'est-à-dire au clic sur un bouton au à la touche entrée.

**Comment by DanFluture275** [comment]
Cloture du ticket, délai passé à 600ms, et on souhaite rester sur une recherche dynamique
