### ISSUE TITLE
Ajout de trendlines

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#375]
Transformer les charts suivants en "Big Number with trendline"

- [ ] Nombre de jeux de données
- [ ] Nombre de jeux de données moissonnés --> à vérifier si la donnée est historisée

Trendline définie sur un mois glissant.

**Comment by DanFluture275** [comment]
Chart initié sur : https://dashboard.data.developpement-durable.gouv.fr/explore/?form_data_key=daEB0DeRRmCggjMV96gIhGDJwMC8X5nbV6Guiz8BJnPydHctsfqptvg9f2XSe0AB&slice_id=50

Semble ok, mais il faudrait ajouter une jointure pour avoir les colonnes nécessaires au fonctionnement du drill down...

**Comment by at-github** [comment]
J'ai ajouté une jointure avec la table metrics dans le dataset, le chart sort le bon chiffre mais tous les autres ont fait augmenté. Je vois ce que je peux faire

**Comment by DanFluture275** [comment]
Je pensais plus créer un nouveau dataset avec la jointure pour ces charts, et garder les mêmes pour le reste des charts du dashboard.

**Comment by at-github** [comment]
> Je pensais plus créer un nouveau dataset avec la jointure pour ces charts, et garder les mêmes pour le reste des charts du dashboard.

@DanFluture275 Du coup le drill down ne fonctionnera pas pour ce chart on est d'accord ?

**Comment by streino** [comment]
Il faut un drill-down cohérent partout, sinon ça sera incompréhensible.
Quitte à avoir 2 dashboards.

**Comment by DanFluture275** [comment]
si on a les mêmes noms de colonne dans les deux datasets, le drill down devrait bien s'appliquer partout. Mais c'est peut-être plus simple d'avoir un seul dataset qui fait la jointure sur toutes les tables, catalog, organisation, distribution et metrics en effet....

**Comment by streino** [comment]
Si le drill down marche avec deux datasets séparés, ça peut valoir le coup de l'envisager s'il y a un vrai gain de perf ? Comme c'est la même moulinette qui générera tout on peut relativement facilement s'assurer que les noms correspondent.

**Comment by at-github** [comment]
Je veux bien un coup de main dans ce cas, car je n'arrive pas à faire une jointure avec la table metrics qui soit pertinente. Et malheureusement je ne vois pas comment avoir un dataset avec toutes les colonnes concernées par le drill down sans faire ces mêmes jointures.

**Comment by DanFluture275** [comment]
Plus d'actu suite mise en place dashboard KPI
