### ISSUE TITLE
[HOME] - Menu

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#391]
Ajout du lien vers la page Organisations listant les pages présentes sur ecologie.data.gouv

![Image](https://github.com/user-attachments/assets/f4f905f1-3a61-4d26-9496-33de63bd58db)

**Comment by at-github** [comment]
https://github.com/opendatateam/udata-front-kit/pull/542

**Comment by abulte** [comment]
@at-github mets plutôt un `Fix https://github.com/ecolabdata/ecospheres/issues/391` dans la description de https://github.com/opendatateam/udata-front-kit/pull/542
