### ISSUE TITLE
[HOME] - Bloc titre + moteur de recherche

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#392]
Mise en place du Titre et du bloc de recherche central

![Image](https://github.com/user-attachments/assets/f1443e32-5de8-4d97-aedc-f0769d3b000a)

Ce bloc de recherche doit avoir le même comportement que le bloc en haut à droite (ajout de la recherche dans les organisations).

**Comment by at-github** [comment]
@abulte du coup il faut gérer la recherche dans organisations avant de faire ce ticket aussi ?

**Comment by abulte** [comment]
> @abulte du coup il faut gérer la recherche dans organisations avant de faire ce ticket aussi ?

Je ne pense pas. En réutilisant le même composant que dans le header, on peut commencer par la version sans organisation dans le dropdown et rajouter l'option plus tard.

**Comment by DanFluture275** [comment]
@at-github Suite aux retours, remplacer le titre par : "Le catalogue des données pour la transition écologique"
![Image](https://github.com/user-attachments/assets/4e29ed7f-fbf6-4a56-883d-f9661880bc23)

Nouvelle maquette : https://www.figma.com/design/goZNoxBnPfhh8awXjnDzY6/Maquettes-2024?node-id=567-18293&t=BuMdiP1UhgKbee1K-4
