### ISSUE TITLE
[HOME] - Bloc guichet d’accès à la donnée

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#393]
Mise en place de ce bloc : 
![Image](https://github.com/user-attachments/assets/7e2b6189-ee8f-4af9-b8df-b3531bdd1e00)

- Lien "Accéder aux données" renvoie vers la page Données : `/datasets`
- Lien "Accéder aux bouquets" renvoie vers la page Bouquets :`/bouquets`
- Lien "Ajouter des données" renvoie dans un premier temps vers la page : `https://www.data.gouv.fr/fr/pages/onboarding/producteurs/`, avant développement de la page dédiée --> #400 
- Lien "Créer un bouquet" renvoie vers la création de bouquet : `/admin/bouquets/add`

Attention au respect des reco RGAA pour les SVG (doc dans la codebase)

**Comment by at-github** [comment]
@thomas-duport @DanFluture275 possible d'avoir un export des images utilisées (même taille, fond transparent) svp ? Je n'arrive pas à le faire proprement

**Comment by ghost** [comment]
Assets envoyés !

**Comment by DanFluture275** [comment]
@at-github suite aux derniers retours : 
- remplacer les picto par les versions vertes
- Mise à jour des textes : 
1er bloc : Accédez à un ensemble de données liées à la transition écologique.
2è bloc : Participez à la centralisation et à la structuration des données de la transition écologique.

![Image](https://github.com/user-attachments/assets/a2bff719-bd2b-44d5-9a10-cddc8db66601)

Nouvelle maquette : https://www.figma.com/design/goZNoxBnPfhh8awXjnDzY6/Maquettes-2024?node-id=567-18455&t=BuMdiP1UhgKbee1K-4

**Comment by at-github** [comment]
@thomas-duport peux-tu me donner un coup de main pour l'export des visuels stp ?
J'ai des difficultés à exporter celui d'explorer sans recadrage (reste du dessin nécessaire pour le mobile)
