### ISSUE TITLE
[HOME] - Bloc derniers bouquets

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#395]
Mise en place de ce bloc : 
![Image](https://github.com/user-attachments/assets/660a8f81-8caf-45e8-910d-0420ff398844)

Dans un premier temps, pas de filtre en haut à droite, ce ticket ne concerne que le développement de l'affichage des derniers bouquets publiés, en attendant de pouvoir sélectionner des bouquets mis en avant (cf ticket #399)
Le lien "Tous les bouquets" renvoie vers la page de liste des bouquets : `/bouquets`
Affichage des trois derniers bouquets au statut publiés uniquement (pas de brouillons)

Créer un nouveau composant, qui pourra également être utilisé sur la page listing (cf #409 )

**Comment by at-github** [comment]
Il y a un défi de mise en page sur le premier élément dû à sa longueur potentiel. J'ai, sur un des 3 derniers bouquets le texte suivant par exemple : "La planification et la différenciation territoriale selon les caractéristiques et les spécificités de chaque territoire, incluant les territoires ultra-marins".
Je pars pour forcer une seule ligne et tronqué le texte sauf contre-indication…

**Comment by DanFluture275** [comment]
Ok pour ce comportement, oui, forcer sur une seule ligne et tronquer le texte si il dépasse. 
Par contre, à la réflexion, on devrait plutôt afficher la thématique que le chantier dans ce "tag".

**Comment by at-github** [comment]
Comme vu ensemble, on affiche bien le chantier en tant que tag
