### ISSUE TITLE
[HOME] - Bloc FAQ

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#396]
Mise en place du mécanisme de FAQ.
![Image](https://github.com/user-attachments/assets/26fc7486-5992-470a-b525-3321242e6b54)

Contenu éditorial de la FAQ détaillé dans le ticket #109

**Comment by at-github** [comment]
@DanFluture275 Aurais-tu les contenus stp ?

**Comment by DanFluture275** [comment]
Les questions sont listées ici, work in progress : [https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/cNT1D4gOhSZAjaxDuq8B/guide-utilisateur-rice/faq](url)

**Comment by at-github** [comment]
> Les questions sont listées ici, work in progress : [https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/cNT1D4gOhSZAjaxDuq8B/guide-utilisateur-rice/faq](url)

Merci, l'accordéon est prêt. Le contenu est stocké dans un objet. J’intègre le contenu dès que c'est prêt

**Comment by DanFluture275** [comment]
Dépendance avec #439 qui doit être fait avant

**Comment by at-github** [comment]
> > Les questions sont listées ici, work in progress : [https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/cNT1D4gOhSZAjaxDuq8B/guide-utilisateur-rice/faq](url)
> 
> Merci, l'accordéon est prêt. Le contenu est stocké dans un objet. J’intègre le contenu dès que c'est prêt

Je n'ai plus accès au contenu, @DanFluture275 tu confirmes que de ton côté non plus stp ?

**Comment by DanFluture275** [comment]
Non, l'accès est ok, c'est juste le lien hypertexte qui était incorrect, mais c'est bien la bonne URL : [https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/cNT1D4gOhSZAjaxDuq8B/guide-utilisateur-rice/faq](https://app.gitbook.com/o/mzU9jtEwFUrzgXYMPncc/s/cNT1D4gOhSZAjaxDuq8B/guide-utilisateur-rice/faq)

**Comment by at-github** [comment]
Curieux je n'ai pas accès, mon compte n'a pas l'air d'être autorisé

**Comment by DanFluture275** [comment]
@at-github Contenu copié sur [https://docs.google.com/document/d/1y-kW6xyzZOpcCz1B1vTRGxAjfL9fGW_MEYlAm6A5_18/edit?usp=sharing](https://docs.google.com/document/d/1y-kW6xyzZOpcCz1B1vTRGxAjfL9fGW_MEYlAm6A5_18/edit?usp=sharing)

**Comment by at-github** [comment]
Merci @DanFluture275 , je pense qu'il manque un mot dans cette partie :

**Je ne trouve pas un jeu de données dans l'onglet "Données" ?** 
Pour qu'un jeu de données soit présent dans l'onglet "Données", il est nécessaire que le jeu de données soit publié sur data.gouv.fr et que l'organisation le produisant soit référencée par ecologie.data.gouv.fr `et .` Si vous souhaitez que votre organisation soit référencée sur ecologie.data.gouv.fr, veuillez nous contacter.

**Comment by DanFluture275** [comment]
C'est corrigé dans le google docs, merci.
