### ISSUE TITLE
[HOME] - Footer

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#397]
Mise en place du footer : 
![Image](https://github.com/user-attachments/assets/20169489-60ed-4924-a223-40f7dbb406f1)

Pour les liens, garder la liste existante ([Plan du site ](https://ecologie.data.gouv.fr/sitemap) | [ Conditions générales d'utilisation ](https://ecologie.data.gouv.fr/terms) | [ Politique de confidentialité ](https://www.data.gouv.fr/fr/suivi/) | [ Accessibilité : non conforme](https://ecologie.data.gouv.fr/accessibility)

Mettre à jour le texte + ajout du titre ecologie.data.gouv

Le lien vers la documentation sera ajouté ultérieurement.

**Comment by at-github** [comment]
@DanFluture275 pour le lien legifrance, c'est bien cette url que l'on veut stp ?
https://www.legifrance.gouv.fr/

**Comment by at-github** [comment]
@DanFluture275 j'ignore le lien Licences de la maquette, en fait je ne touche à aucun des liens de cette ligne

**Comment by DanFluture275** [comment]
oui, c'est ça

**Comment by DanFluture275** [comment]
@at-github Nouveau texte footer : "Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à la transition écologique et énergétique, réalisé par le [Ministère de la Transition écologique, de l'Énergie, du Climat et de la Prévention des risques](https://www.ecologie.gouv.fr/).

**Comment by at-github** [comment]
> [@at-github](https://github.com/at-github) Nouveau texte footer : "Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à la transition écologique et énergétique, réalisé par le [Ministère de la Transition écologique, de l'Énergie, du Climat et de la Prévention des risques](https://www.ecologie.gouv.fr/).

Si je ne me trompe pas, la seule différence est le lien.
Sauf erreur, le composant DSFR footer, ne semble pas prêt à recevoir un lien / html

**Comment by DanFluture275** [comment]
Ok, sans le lien alors. Le texte n'est pas tout à fait le même, attention.
