### ISSUE TITLE
[BUG] - Discussions - bouton se connecter

### ISSUE THREAD

**Issue by narduin** [ecolabdata/ecospheres#401]
Dans les dicsussions, quand on veut démarrer/répondre sans être connecté la fonction suivante délenche une erreur:

```js
const triggerLogin = () => {
  LocalStorageService.setItem('lastRoute', route)
  router.push({ name: 'login' })
}
```

Peut-être un problème avec le local storage.

--> Le bouton "Connectez-vous pour démarrer une discussion" dans l'onglet discussion d'une page bouquet est inactif.
Comportement attendu : Redirection vers le process d'authentification. 
![Image](https://github.com/user-attachments/assets/c4f8fcda-3435-41b5-939e-d296d4591195)

**Comment by at-github** [comment]
Ça va être délicat, je ne reproduis pas en local, sur demo et prod oui par contre

**Comment by at-github** [comment]
Le stringify échoue avec le objet `route` à cause d'une référence circulaire (pas en dev)
Pour l'instant j'ai du mal à mettre le doigt dessus

**Comment by DanFluture275** [comment]
@abulte Pas possible de rediriger directement sur l'onglet Discussions après l'authent, quand on vient du bouton "Connectez-vous pour démarrer une discussion" ? 

Sinon,  j'ai également vu une erreur de Cors Policy quand on répond à une discussion, il faut cliquer plusieurs fois sur Soumettre pour que ça passe. Hors périmètre de ce ticket, car je reproduis aussi sur d'autres environnements, j'ouvre un nouveau ticket sur ce point.
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/6b6589bc-5170-4b72-9858-51c935f3bc0b">

**Comment by abulte** [comment]
> @abulte Pas possible de rediriger directement sur l'onglet Discussions après l'authent, quand on vient du bouton "Connectez-vous pour démarrer une discussion" ?

Peut-être possible mais pas évident et hors scope du ticket.
