### ISSUE TITLE
Bug bouton "Connectez-vous pour démarrer une discussion"

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#403]
Le bouton "Connectez-vous pour démarrer une discussion" dans l'onglet discussion d'une page bouquet est inactif.
Comportement attendu : Redirection vers le process d'authentification. 
![Image](https://github.com/user-attachments/assets/c4f8fcda-3435-41b5-939e-d296d4591195)

**Comment by abulte** [comment]
Duplicate #401
