### ISSUE TITLE
Lisibilité bouton Fermer modale édition facteur

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#405]
Dans la page d'édition de facteur, il faudrait passer le texte en clair au hover pour qu'il reste lisible.

![Image](https://github.com/user-attachments/assets/d5ea65d0-6475-426f-b40d-1ca0eb909d10)

**Comment by narduin** [comment]
Il faut ajouter la classe `fr-btn--close` dans le `:not(...)` [main.css](https://github.com/opendatateam/udata-front-kit/blob/main/src/assets/main.css#L142-L147)
