### ISSUE TITLE
Mettre à jour le composant barre de recherche sur toutes les pages

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#407]
Mettre en cohérence le composant recherche sur toutes les pages sur le modèle de celui implémenté dans le header.
(page données, avec recherche uniquement sur les données et page bouquets avec recherche uniquement sur les bouquets).

**Comment by DanFluture275** [comment]
A faire après : 
- le merge de la PR dette technique mise à jour des librairies
- le merge de la PR refonte de la home (pour l'ajout du nouveau composant barre de recherche)

Puis utiliser le composant développé pour la home

**Comment by at-github** [comment]
Il y a une petit réflexion à avoir concernant le dropdown, qui est consulté depuis la config. Je creuse

**Comment by at-github** [comment]
Le style aussi est à refaire, le composant est complètement différent quand on désactive le dropdown

**Comment by at-github** [comment]
Et sans dropdown il faut que je trouve un moyen de préciser où il doit chercher. Ça ne se comporte pas comme un simple input, mais plutôt un form

**Comment by at-github** [comment]
Mes tests anti-regressions :
- Recherche fonctionnelle dans le header
  - Recherche dans les bouquets
  - Recherche dans les données
- Idem sur la home
- Recherche fonctionnelle depuis la page bouquets
- Idem depuis la page données
- Champs et recherche en visitant la page bouquets avec une query dans l'url
- idem pour la page données
- Réinitialisation effective sur bouquets & données
