### ISSUE TITLE
Mettre à jour les cards bouquets dans le listing

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#409]
Mettre à jour le composant cards dans le listing des bouquets pour qu'il corresponde au nouveau design implémenté sur la home.
@thomas-duport design à fournir

**Comment by ghost** [comment]
Design créé : https://www.figma.com/design/goZNoxBnPfhh8awXjnDzY6/Maquettes-2024?node-id=483-19568&node-type=section&t=KUuy305588n2j1jr-11
