### ISSUE TITLE
Ajouter un title sur le champs rechercher

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#419]
Paragraphe 14  du rapport de contre-audit : 

Toutes les pages sauf la page 03
11.1 Majeur : Absence d’étiquette
Ajouter un title=”Rechercher” sur l’élément <input>

**Comment by narduin** [comment]
Pas possible d'ajouter un attribut car c'est un composant mais j'ai pu ajouter un texte visible (ignoré par les lecteurs d'écrans). Ça devrait être conforme.
