### ISSUE TITLE
404 sur export bouquet

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#427]
https://demo.ecologie.data.gouv.fr/bouquets/elaboration-ou-evolution-dun-document-durbanisme-haute-savoie

![image](https://github.com/user-attachments/assets/1f5e804f-9f64-4ea1-aaa6-891006b9855b)

Ajouter un code "Remote deleted" pour ce cas de figure dans la colonne Availability, et le traiter comme "Missing" pour le reste (ne pas afficher les infos du JDD)

**Comment by streino** [comment]
Bloquant pour la presta "reco" de Wavestone, qui a besoin d'exporter les bouquets avec leurs liste de facteurs.

@DanFluture275 si on peut passer ça dans l'itération en cours c'est top. Sans doute moins de boulot que d'essayer d'exporter les bouquets autrement.

**Comment by DanFluture275** [comment]
Ok oui, prenons le dans le sprint 4. Il semble qu'il n'y ait que ce bouquet qui soit concerné, je n'ai pas réussi à reproduire sur d'autres bouquets. Une idée de la cause ?

**Comment by abulte** [comment]
C'est à cause d'un jeu de données référencé dans le bouquet puis supprimé sur demo.data.gouv.fr, un impact qui n'a pas été géré dans #221.

404 sur https://demo.data.gouv.fr/api/2/datasets/66e488ac6c41fa9da515ad1b/

<img width="936" alt="Capture d’écran 2024-10-31 à 09 57 25" src="https://github.com/user-attachments/assets/6338c385-a46a-4b24-9533-347cbd22306f">

Pour débloquer Wavestone, j'enlève l'association de ce jeu de données dans ce bouquet. Le bug reste et devrait être facile à reproduire sur un bouquet de test.

**Comment by at-github** [comment]
Petit rapport :

1 - Tentative de reproduire le bug sans succès coté front (création d'un bouquet, avec une donnée valide et une donné avec une l'url pointant sur une 404)
2 - Je regarde le code de https://github.com/ecolabdata/ecospheres-dashboard-backend & je galère pour l'instant à trouver la partie responsable de mettre la bonne valeur à la colonne availability

**Comment by abulte** [comment]
C'est un peu tricky à reproduire : il faut référencer un jeu de données depuis demo.data.gouv.fr, puis le supprimer.

Tu peux utiliser ce bouquet de test https://demo.ecologie.data.gouv.fr/bouquets/bouquet-alb-supprime-et-archive.

Il n'y aucun rapport avec https://github.com/ecolabdata/ecospheres-dashboard-backend, la colonne `availability` est calculée par le front et stockée dans / récupérée depuis data.gouv.fr par le front également.

**Comment by at-github** [comment]
> C'est un peu tricky à reproduire : il faut référencer un jeu de données depuis demo.data.gouv.fr, puis le supprimer.
> 
> Tu peux utiliser ce bouquet de test e.
> 
> Il n'y aucun rapport avec https://github.com/ecolabdata/ecospheres-dashboard-backend, la colonne `availability` est calculée par le front et stockée dans / récupérée depuis data.gouv.fr par le front également.

Merci, effectivement rien à voir avec le dashboard, fausse piste de ma part, désolé pour le bruit.
Comment avoir le bouquet d'eexemple en local stp 🙏🏻 ?

**Comment by abulte** [comment]
> Merci, effectivement rien à voir avec le dashboard, fausse piste de ma part, désolé pour le bruit. Comment avoir le bouquet d'eexemple en local stp 🙏🏻 ?

http://localhost:5173/bouquets/bouquet-alb-supprime-et-archive

**Comment by at-github** [comment]
> > Merci, effectivement rien à voir avec le dashboard, fausse piste de ma part, désolé pour le bruit. Comment avoir le bouquet d'eexemple en local stp 🙏🏻 ?
> 
> http://localhost:5173/bouquets/bouquet-alb-supprime-et-archive

Merci je ne le voyais pas dans la liste, j'ai cru qu'il fallait un import ou autre
