### ISSUE TITLE
JDD supprimé de Géo-IDE apparaît encore sur demo.data.gouv

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#457]
Le CSW renvoie 115 records. On en a 132 sur demo.

Exemple de fiche de métadonnées dépubliée sur GéoIDE et qui apparaît encore sur demo :

> iru : 15f74366-5885-4cd9-8343-cd76c489dca8
> Zones agricoles défavorisées dans l'Indre-et-Loire
> N_DEFAVORISEE_ZSUP_037 : dans répertoire AGRICULTURE / N_ZONAGES_AGRICOLES.

https://demo.data.gouv.fr/fr/datasets/zones-agricoles-defavorisees-dans-lindre-et-loire-1/

Le GetRecordById sur cet fr-120066022-jdd-02056546-7ec6-4ba0-b56a-0cf5414dfa9c ne renvoie rien.

**Comment by abulte** [comment]
Archivage pas encore fait ?

**Comment by streino** [comment]
Normalement le délai est passé à 0 jours sur demo, et ça fait plusieurs jours que l'ADL surveille.

**Comment by abulte** [comment]
A vérifier parce que last_update à 2024-11-04 02:44:47.553000, vs 2024-11-06 pour les autres jdd, ça fait vraiment penser à ça.

**Comment by streino** [comment]
cc @maudetes pour confirmer le délai d'archivage ?

**Comment by maudetes** [comment]
Oups, c'était pas passé parce qu'on faisait un `if 0`. J'ai modifié rapidement à 1 jour de délai pour que ça passe ^^'

**Comment by abulte** [comment]
Archivé sur demo.data.gouv.fr, ainsi que 16 autres. Pour moi c'est bon, à rouvrir sinon.

<img width="249" alt="Capture d’écran 2024-11-07 à 17 05 40" src="https://github.com/user-attachments/assets/481639ee-5788-4787-927a-6448d9a7e8c7">

**Comment by streino** [comment]
Oui ça a l'air bon, certaines DDT qui avaient remonté le problème ont signalé que c'était réglé.
