### ISSUE TITLE
[MD] Vérifier la gestion identique des identifiants entre moissonneurs DCAT et DCAT-via-CSW

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#46]
Les deux moissonneurs ont bien le même mapping des identifiants ?
Voir détails sur les identifiants dans https://github.com/ecolabdata/ecospheres/issues/29

**Comment by streino** [comment]
Moissonnage identique entre DCAT et CSW-DCAT : 
- `dataset.harvest.remote_id` (JDD-ID): [DcatBackend](https://github.com/opendatateam/udata/blob/55efc3ba2b2bdc66de92bcd127d31fa5329fa626/udata/harvest/backends/dcat.py#L134) et [CswDcatBackend](https://github.com/opendatateam/udata/blob/55efc3ba2b2bdc66de92bcd127d31fa5329fa626/udata/harvest/backends/dcat.py#L223) utilisent tous deux `DCT.identifier`. 
- `dataset.harvest.dct_identifier` (JDD-ID): [codepath commun](https://github.com/opendatateam/udata/blob/55efc3ba2b2bdc66de92bcd127d31fa5329fa626/udata/core/dataset/rdf.py#L599) utilisant `DCT.identifier`.
- `dataset.harvest.remote_url` (MD-ID): [codepath commun](https://github.com/opendatateam/udata/blob/55efc3ba2b2bdc66de92bcd127d31fa5329fa626/udata/core/dataset/rdf.py#L440) utilisant `DCAT.landingPage` avec fallback sur `DCT.identifier`.

OK mais incomplet à la rééexposition : 
- `DCT.identifier` (JDD-ID): [codepath commun](https://github.com/opendatateam/udata/blob/c9f67600e2dc78103747356fd2d63602534be758/udata/core/dataset/rdf.py#L189) utilisant `dataset.harvest.dct_identifier` dans le cas d'un dataset moissonné.
- ? = `rdflib.Resource.identifier` (MD-ID): [code commun](https://github.com/opendatateam/udata/blob/55efc3ba2b2bdc66de92bcd127d31fa5329fa626/udata/core/dataset/rdf.py#L181) utilisant `dataset.harvest.uri`.
- `dataset.harvest.remote_url` ne semble pas exposé actuellement.

@maudetes tu confirmes ?

**Comment by maudetes** [comment]
L'analyse me semble correcte !
