### ISSUE TITLE
Espacement nom de l'utilisateur (header)

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#473]
Au niveau du header, espacements incohérents entre le nom de l'utilisateur et les boutons "Donnez votre avis" et "Déconnexion". 

~Bien que le nom d'utilisateur ne renvoie pas vers un lien, sa couleur détonne également avec celle des deux autres boutons.~

![image](https://github.com/user-attachments/assets/a5ce38ce-cc5a-4a74-9d73-aa85c04a56c0)

**Comment by at-github** [comment]
La partie espacement est claire. Pour la partie couleur, dois-je utiliser la couleur des liens même si ce n'en est pas un ?

**Comment by at-github** [comment]
À noter que je n'ai pas le même rendu sur la branche `main` en local et sur https://demo.ecologie.data.gouv.fr/
![Image](https://github.com/user-attachments/assets/c432563c-44d2-400f-bb6f-f0c47b1c7bf7)
