### ISSUE TITLE
Supprimer components.d.ts du git

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#487]
Cf https://ecosphres.slack.com/archives/C07KNCLLEJW/p1732010637847759

Vérifier également si on peut supprimer auto-import.d.ts du git.

**Comment by narduin** [comment]
À priori il faut laisser `auto-import.d.ts` [d'après le développeur](https://github.com/unplugin/unplugin-auto-import/issues/288#issuecomment-1301691329) de la lib.
