### ISSUE TITLE
Appels CDN pour les icônes

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres#497]
Depuis #406 (?), on interroge un CDN pour récupérer les icônes, e.g. https://api.iconify.design/ri.json?icons=add-circle-line sur https://demo.ecologie.data.gouv.fr/datasets.

En tant que site institutionnel, on se doit d'éviter ce genre de pratiques (ou alors il faut vraiment bien lire et faire valider les conditions d'utilisation du dit CDN), il y potentiellement du tracking qui est fait (sans consentement explicite de l'usager) et on dépend d'un service tiers qu'on ne maîtrise pas.

Idéalement, il faudrait s'en débarrasser. Voir aussi ce que dit le DSFR et/ou vue-dsfr à ce sujet.

**Comment by DanFluture275** [comment]
- Commencer par demander à l'équipe vue dsfr si il existe une solution.

**Comment by abulte** [comment]
Cf https://github.com/dnum-mi/vue-dsfr/discussions/969
