### ISSUE TITLE
Problème cohérence nombre d'organisations

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#502]
Vérifier le mode de calcul du nombre d'organisations et le mettre en cohérence dans le calcul des métrics
(actuellement 173 orga dans les metrics, et 171 dans le filtre du dashboard  patrimoine)

**Comment by abulte** [comment]
```
dashboard_backend_prod=# select count(distinct(organization)) from catalog where deleted = false;
 count
-------
   171
(1 row)
```
