### ISSUE TITLE
Simplifier les droits en écriture sur les bouquets

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres#512]
En tant qu'administrateur du site logistique.data.gouv.fr, je souhaite qu'un utilisateur hérite des droits lié à son organisation data.gouv.fr pour les droits d'édition d'un bouquet appartenant à la même organisation, afin de ne plus avoir à gérer les accès dans un fichier de config yaml.

cf https://github.com/opendatateam/udata-front-kit/issues/622

**Comment by abulte** [comment]
> En tant qu'administrateur du site ecologie.data.gouv.fr

Rien à voir avec ecologie.data.gouv.fr, on n'utilise pas ce système de gestion de pseudo-droits. C'est spécifique à certaines verticales comme logistique.data.gouv.fr.

**Comment by DanFluture275** [comment]
qui est le personna visé par cette évolution alors ?

**Comment by abulte** [comment]
Un administrateur du site logistique.data.gouv.fr.

**Comment by streino** [comment]
Dans ce cas est-ce que ça nous concerne ici, ou on tag "logistique" sur le ticket front-kit et on laisse logistique s'en occuper ?

**Comment by DanFluture275** [comment]
Ne sera pas traité coté ecologie.data.gouv.fr qui n'est pas concerné par le problème.
