### ISSUE TITLE
Associer une zone géographique à un bouquet

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres#74]
Trois possibilités, par ordre de préférence :
1. avoir le champ côté data.gouv.fr et l'utiliser sur le front, cf https://github.com/opendatateam/udata/pull/2988
2. utiliser le référentiel de data.gouv.fr, cf https://github.com/ecolabdata/ecospheres/issues/74#issuecomment-1982967314 et stocker la zone en extras
3. utiliser un champ libre, cf https://github.com/ecolabdata/ecospheres/issues/74#issuecomment-1981047872

Le endpoint de suggest sur les zones (basées sur le COG) fonctionne bien pour utilisation dans un select, comme dans le backoffice de data.gouv.fr https://www.data.gouv.fr/api/1/spatial/zones/suggest/?q=poiss&size=10&lang=fr&_=1710148345953

**Comment by streino** [comment]
Voir avec data.gouv ce qu'on peut faire d'ici la release interco.
En fallback, prévoir un champ libre en attendant l'implémentation d'une solution basée sur référentiel.

**Comment by abulte** [comment]
A quoi servirait un champ libre ? Il faudra de toute façon prévoir une reprise manuelle, donc on pourra assigner la bonne métadonnée depuis le référentiel à ce moment là, non ?

**Comment by streino** [comment]
Juste pour stocker l'info le temps d'avoir le référentiel.
L'autre possibilité est de le documenter dans la description du bouquet, comme on avait suggéré pour l'orga. Mais ça peut commencer à faire un template complexe à respecter dans la description.

**Comment by abulte** [comment]
Le référentiel data.gouv.fr :
- https://doc.data.gouv.fr/api/reference/#/spatial
- https://www.data.gouv.fr/api/1/spatial/levels/
- https://www.data.gouv.fr/api/1/spatial/coverage/fr:departement/

Endpoint lent, en cours d'investigation data.gouv.fr.

**Comment by abulte** [comment]
@martyKN Tu as une idée de où rajouter ce champ dans le parcours de création / édition ? Peut-être avec les thèmes / sous-thèmes ?
