### ISSUE TITLE
Associer une organisation à un bouquet

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres#89]
Depends on ecolabdata/udata-front-kit#94 
Depends on ecolabdata/udata-front-kit#104

**Comment by streino** [comment]
En attendant #14, on pourrait : 
- sélectionner une/des orgas auxquelles il appartient lors du parcours de création (à prendre en compte dans #141)
- afficher la/les orgas dans l'encart MD du bouquet
- autoriser les utilisateurs appartenant à la/les orgas du bouquet à éditer le bouquet

**Comment by streino** [comment]
> * sélectionner une/des orgas auxquelles il appartient lors du parcours de création
> * afficher la/les orgas dans l'encart MD du bouquet
> * autoriser les utilisateurs appartenant à la/les orgas du bouquet à éditer le bouquet

@abulte Ca serait faisable sans modifs upstream ? Et sans trop jeter de code une fois qu'on aura #14 ?

**Comment by abulte** [comment]
Oui faisable je pense. Reste à voir ce qu'il y a dans #14 précisément pour évaluer la quantité de code à jeter :-)

**Comment by streino** [comment]
@martyKN @Thesauruv Est-ce que vous y voyez un intérêt en attendant #14 ?

**Comment by martyKN** [comment]
> @martyKN @Thesauruv Est-ce que vous y voyez un intérêt en attendant #14 ?

tout dépend quand la #14 sort de terre :)

**Comment by streino** [comment]
Pas de visibilité à ce stade, mais IMO pas avant l'été.

**Comment by streino** [comment]
data.gouv est toujours dans la phase de conception, ça n'a pas l'air facile de sortir une fonctionnalité qui met tout le monde d'accord.

Donc IMO à envisager de notre côté car l'attente risque d'être plus longue que prévue.

**Comment by martyKN** [comment]
> data.gouv est toujours dans la phase de conception, ça n'a pas l'air facile de sortir une fonctionnalité qui met tout le monde d'accord.
> 
> Donc IMO à envisager de notre côté car l'attente risque d'être plus longue que prévue.

OK, quel serait le MVP sur cette fonctionnalité.
IMO un brouillon éditable par un ensemble de users (appartenant ou non à une orga commune TBD)

**Comment by streino** [comment]
Gérer un ensemble de users arbitraires va être plus compliqué qu'une orga, car on ne peut même pas s'appuyer sur l'objet orga existant de data.gouv. @abulte tu en penses quoi ?

Sinon dans un premier temps imposer une orga commune ? Quitte à ce que les gens créent des orgas "spéciales bouquets" ? Si on va dans cette direction, peut-être faut-il distinguer l'orga détentrice du bouquet (affichée dans l'encart MD) de l'orga éditrice (moins visible, sans doute uniquement par les éditeurs). Pas certain que ça soit du scope du MVP d'avoir cette distinction cependant.

**Comment by abulte** [comment]
Oui le MVP c'est clairement associer une orga à un bouquet et utiliser les droits sur l'orga pour gérer les bouquets. Quitte à créer des orga dédiées au besoin.

**Comment by streino** [comment]
> - sélectionner une/des orgas auxquelles [l'éditeur] appartient lors du parcours de création [1 seule orga pour le MVP]
> - afficher la/les orgas dans l'encart MD du bouquet
> - autoriser les utilisateurs appartenant à la/les orgas du bouquet à éditer le bouquet

Autre chose ?
Un chti design pour le premier point ? @martyKN

**Comment by martyKN** [comment]
> > * sélectionner une/des orgas auxquelles [l'éditeur] appartient lors du parcours de création [1 seule orga pour le MVP]
> > * afficher la/les orgas dans l'encart MD du bouquet
> > * autoriser les utilisateurs appartenant à la/les orgas du bouquet à éditer le bouquet
> 
> Autre chose ? Un chti design pour le premier point ? @martyKN

je vois que @abulte a deja fait la màj !

**Comment by streino** [comment]
> > Autre chose ? Un chti design pour le premier point ? @martyKN
> 
> je vois que @abulte a deja fait la màj !

Yep, du coup ça te convient ?
