### ISSUE TITLE
Rechercher des bouquets par mots-clés

### ISSUE THREAD

**Issue by bonjourmauko** [ecolabdata/ecospheres#90]
#### Rechercher (trouver) un bouquet

Utilisateur: agent / consommateur de données

Lorsque je dois rédiger un rapport avec un indicateur,
je veux savoir si les données pertinentes existent,
afin de remplir encore mieux ma mission de service public.

### Contexte ou situation

Lorsque j'utilise la barre de recherche au milieu de la page d'accueil,
je m'attends à ce qu'il me soit proposé de cherche des bouquets.

Quelque chose comme cela (de data.gouv.fr) :

<img width="434" alt="Screenshot 2023-11-24 at 06 36 49" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/7bd26fb9-f92f-4794-9b13-e0c09747fff9">

### Problème rencontré par les utilisateurs

Ce n'est pas le cas. La barre du milieu n'offre que la recherche par dataset.

<img width="1292" alt="Screenshot 2023-11-24 at 06 38 24" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/8e2f0f65-dcbd-4736-9c1f-1ec851d3182b">

### Proposition de solution au problème

Quand je suis dans la page d'accueil d'Écosphères,
Je ne vois qu'une seule barre de recherche (au milieu de la page),
Qui me propose de rechercher par dataset et par bouquet,

<img width="1261" alt="Screenshot 2023-11-24 at 06 40 25" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/dfc3f66d-efe3-466d-aa4c-3167c5cead8e">

J'écris donc bouquet sur la barre de recherche,
Et un choix m'est proposé entre « Recherche par jeux de données » et « Recherche par bouquet »

TODO @martyKN : écrans.

<img width="434" alt="Screenshot 2023-11-24 at 06 36 49" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/3d464f51-3dea-4739-b43d-0eeeae67af8c">

Je presse Enter et rien ne se passe,
Mais les flèches du clavier et la souris me montrent qu'il y a un choix à faire,
Je choisis donc « Bouquets » avec les flèches du clavier,
Je presse Enter une nouvelle fois,
Et j'arrive sur une page de résultats de la recherche.

TODO @martyKN : écrans.

<img width="1881" alt="Screenshot 2023-11-24 at 06 51 31" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/f49830bc-d53f-4c2d-b96f-9ad15846c904">

Je note que la barre de recherche au milieu a disparu,
Et qu'un barre de recherche avec les mot-clés que j'ai utilisés est apparue un haut à droite,
Ainsi que des filtres par « Thématique » et par « Chantier » à gauche.

J'utilise donc les filtres « Se nourrir » et « Alimentation »,
Et les resultats de ma recherche se raffinent,
Sans écraser la recherche initiale.

TODO @martyKN : écrans.

<img width="1881" alt="Screenshot 2023-11-24 at 06 51 31" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/2560e550-7819-4dc3-9928-87fbb1da64a5">

### Éléments supplémentaires de ma proposition

- Les deux barres de recherche : 
  - ont exactement le même comportement
  - change seulement le style
- La recherche de topics par mot-clé est documentée [ici](https://doc.data.gouv.fr/api/reference/#/topics/list_topics) (`GET /topics/?q=%s`)
- Quand il n'y a pas de résultats, je vois un message sympa ecolabdata/udata-front-kit#164 
- @streino proposait de mettre un `v-if=config.truc` pour que la disparition des barres de recherche soit conditionnel à une valeur dans le fichier config.

### Définition de fini

- [ ] L'utilisateur peut choisier entre chercher par bouquet ou par dataset
- [ ] L'utilisateur peut filtrer les résultats de sa recherche par thématique
- [ ] L'utilisateur peut filtrer les résultats de sa recherche par chantier
- [ ] Une application de prévisualisation déployée où tester cette fonctionnalité
- [ ] Un test d'intégration sur ce parcours
- [ ] Des type hints à jour et testés automatiquement
- [ ] Du linting et du formatage du code vérifiés automatiquement

**Comment by abulte** [comment]
@streino j'ai créé une issue spécifique pour les filtres ici https://github.com/ecolabdata/ecospheres/issues/134, peut-être garder celle-ci pour la recherche "full-text" uniquement ?

**Comment by streino** [comment]
Voir si/quand on peut utiliser la searchbar multi-type de data.gouv
