### ISSUE TITLE
Afficher date et owner d'un bouquet

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ecospheres#91]
Quand j'arrive sur un bouquet je voudrais connaitre

- sa date de réalisation et/ou sa date de dernière modification
- l'organisation qui l'a crée et/ou la personne physique

**Comment by abulte** [comment]
WIP design page bouquet https://www.figma.com/file/YmsbJVui0zKVAHNx9NPFAA/Bouquets?type=design&node-id=3319-25470&mode=design&t=jgYf6aqsWPiQXoyF-0
