### ISSUE TITLE
Réordonner des jeux de données dans un bouquet

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#93]
Actuellement, il n'est pas possible de modifier l'ordre apparent des jeux de données référencés dans un bouquet. L'ordre des jeux de données est important afin de mettre d'abord en avant les jeux de données les plus importants mais aussi de regrouper ceux qui présentent davantage de liens.

**Comment by abulte** [comment]
- https://draggable-docs.vueflow.dev
- https://github.com/SortableJS/vue.draggable.next

**Comment by abulte** [comment]
Depends #357 (touche aux mêmes composants)
