### ISSUE TITLE
Intégration d'un Net Promoter Score

### ISSUE THREAD

**Issue by Thesauruv** [ecolabdata/ecospheres#94]
[A discuter] 

Nous souhaitons obtenir depuis la plateforme une évaluation du niveau de recommandation. Concrètement, il s'agirait d'intégrer une  échelle d'évaluation de produit, au niveau des bouquets ou dans la page d'accueil.

**Comment by abulte** [comment]
A voir si on peut utiliser https://observatoire.numerique.gouv.fr/je-donne-mon-avis

**Comment by streino** [comment]
La solution "Je donne mon avis" suggérée par @abulte ne fonctionne pas exactement sur une base de NPS mais permet d'avoir une note de satisfaction sur 10 en faisant un calcul basé sur les 5 questions du formulaire ci-dessous (toutes les questions sauf la première étant optionnelles) :

<img src="https://observatoire.numerique.gouv.fr/download/Aide/Donner%20son%20avis/JDMAEtape2.png?width=400"/>

Derrière on récupère ça comme stats :

https://observatoire.numerique.gouv.fr/Demarches/1223?view-mode=statistics&date-debut=2021-07-01&date-fin=2022-06-30

C'est très orienté "démarche" (en particulier question 3), mais ça a les énormes avantages de ne nécessiter aucun dev/hosting et d'être ok RGPD/RGAA.

@Thesauruv @martyKN vous en pensez quoi ?

Et si ça ne convient pas, vous connaissez des alternatives ?

**Comment by streino** [comment]
Sinon meteo.data.gouv utilise tally.
Ca semble finalement pas trop mal niveau RGPD : https://tally.so/help/gdpr

**Comment by Thesauruv** [comment]
Le NPS est visiblement calculé à partir du renseignement direct de la satisfaction sur une échelle de 0 à 10. Le tally de meto.data.gouv respecte ce principe. Je ne saurais pas dire la solution de "Je donne mon avis" donne indication plus fiable sur les promoteurs. Dans le doute, je resterais pour la solution tally avec un calcul direct. 

Est-ce qu'on obtient également un résumé des statistiques en sortie du tally ?

**Comment by martyKN** [comment]
je vote pour le tally de meteo.dg.fr qui respecte le NPS. 
Ca soulève une possibilité si on se met a utiliser un tally à plusieurs niveaux et à plusieurs personnes => avoir une licence pro. Je sais que Beta a une licence qu'ils distribuent aux beta grouveurs•euses

**Comment by streino** [comment]
Le tally en cours d'élaboration : https://tally.so/r/wLWrzp
