### ISSUE TITLE
Liens externes et mentions légales en footer

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#97]
Liste des liens externes à faire figurer : 
- [x] ecologie.gouv.fr
- [x] data.gouv.fr
- [x] gouvernement.fr

Liste des mentions légales à faire figurer :
- [x] Accessibilité
- [ ] ~~Conditions d'utilisation~~ (cf #112)
- [x] Politique de confidentialité (ok de réutiliser celle de data.gouv car on est sur leur matomo)
- [x] ~~Licences~~ (pas nécessaire, cf gouvernement.fr, legifrance.gouv.fr, ...)

**Comment by martyKN** [comment]
Beta propose un générateur d'accessibilité https://betagouv.github.io/a11y-generateur-declaration/#create

**Comment by streino** [comment]
Pour les conditions d'utilisation, je sors ça dans un autre ticket car ça risque de prendre du temps https://github.com/ecolabdata/ecospheres/issues/112.
