### ISSUE TITLE
Page d'accueil

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres#99]
Expliciter le fait que la barre de recherche porte sur les données et que la navigation FNV porte sur les bouquets, ou revoir l'approche.

Alexandra travaille sur un schéma explicatif des bouquets.
Besoin d'expliquer ce qu'est un bouquet.

Des actualités sur la page d'accueil ?

**Comment by martyKN** [comment]
<img width="770" alt="Capture d’écran 2024-03-04 à 11 31 06" src="https://github.com/ecolabdata/ecospheres/assets/74351881/a9073298-7f88-4119-ad1c-fc9b3a5f8288">
l'avancée de la page d'accueil est in progress mais c'est pas encore ca

**Comment by martyKN** [comment]
visuels pour la home **release mars** et **cible**
https://www.figma.com/file/YmsbJVui0zKVAHNx9NPFAA/Bouquets?type=design&node-id=2936%3A124498&mode=design&t=AHzRlwJOBVPqi9L3-1
